In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('probability_laws_customer_sessions.csv')
df.head()

,session_id,region,age_group,traffic_source,experiment_group,premium_member,used_mobile_app,ad_clicked,email_opened,coupon_used,visit_count_30d,engagement_level,purchased,payment_method,order_value_usd,returned_order,support_contacted,churned,fraudulent_transaction,fraud_alert
0,S0001,North,18-24,Social Media,A,Yes,Yes,No,No,Yes,4,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
1,S0002,West,45+,Organic,A,No,No,No,No,No,0,Low,No,NaN,0.0,Not Applicable,No,Yes,No,No
2,S0003,East,35-44,Organic,A,No,Yes,No,No,No,4,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
3,S0004,East,35-44,Paid Search,A,Yes,Yes,No,No,No,5,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
4,S0005,East,35-44,Organic,B,Yes,No,Yes,No,Yes,5,Medium,No,NaN,0.0,Not Applicable,No,No,No,No

## First combination


`Question:` What is the proportion of customers purchased and used a coupon ?
- Event A - Customers used cupon
- Event B - Customers purchased

### Event operations

In [4]:
cupon_purchase = df[['coupon_used', 'purchased']]
cupon_purchase.head()

  coupon_used purchased
0         Yes        No
1          No        No
2          No        No
3          No        No
4         Yes        No

#### Intersection

In [5]:
intersection_A_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') & 
    (cupon_purchase['purchased'] == 'Yes')
]
len(intersection_A_B)

190

#### Union

In [6]:
union_A_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') |
    (cupon_purchase['purchased'] == 'Yes')
]
len(union_A_B)

583

#### Complement

In [7]:
not_event_A = cupon_purchase[cupon_purchase['coupon_used'] != 'Yes']
len(not_event_A)

921

In [8]:
not_event_B = cupon_purchase[cupon_purchase['purchased'] != 'Yes']
len(not_event_B)

706

### Event Relationships

- Event A - Customers used cupon
- Event B - Customers purchased

#### Mutually Exlusive


`A event using a coupon` and `B event purchasing` may be happen at the same time so, these events are not **Mutually Exlusive**

In [9]:
not_mutually_exclusive_A_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') & 
    (cupon_purchase['purchased'] == 'Yes')
]
not_mutually_exclusive_A_B.head()

   coupon_used purchased
16         Yes       Yes
18         Yes       Yes
46         Yes       Yes
67         Yes       Yes
71         Yes       Yes

#### Independent vs Dependent Events

Whether the two events are independent or Dependent ?

##### Method-1:

- When two events are independent P(A ∩ B) = P(A) × P(B)​                                                                                        
- When two events are dependent   P(A ∩ B) ≠ P(A) × P(B)​

In [10]:
event_A = cupon_purchase[cupon_purchase['coupon_used'] == 'Yes'] 
event_B = cupon_purchase[cupon_purchase['purchased'] == 'Yes']
event_A_and_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') &  
    (cupon_purchase['purchased'] == 'Yes')
]

n = len(cupon_purchase)

p_A = len(event_A) / n
p_B = len(event_B) / n
p_A_and_B = len(event_A_and_B) / n

independence_probability = p_A * p_B


print("P(A):", p_A)
print("P(B):", p_B)
print("P(A ∩ B):", p_A_and_B)
print("P(A) × P(B):", independence_probability)

if p_A_and_B == independence_probability:
    print("Events A and B are independent. Because P(A ∩ B) = P(A) * P(B)")
else:
    print("Events A and B are dependent. Because P(A ∩ B) != P(A) * P(B). ")

P(A): 0.2325
P(B): 0.4116666666666667
P(A ∩ B): 0.15833333333333333
P(A) × P(B): 0.0957125
Events A and B are dependent. Because P(A ∩ B) != P(A) * P(B).

##### Method - 2:

- When two events are independent P(B | A) = P(B)
- When two evets are dependent    P(B | A) ≠ P(B) 

P(B | A) = P (A ∩ B) / P(A)

In [11]:
# events
event_A_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') &  
    (cupon_purchase['purchased'] == 'Yes')
]
event_A = cupon_purchase[cupon_purchase['coupon_used'] == 'Yes']
n = len(cupon_purchase)

# probabilities
p_A =  len(event_A) / n
p_B_given_A = len(event_A_B) / len(event_A)


print(f"Probability of A {p_A}")
print(f"Probability of B given A {p_B_given_A}")


if p_B_given_A == p_B:
    print("Events A and B are independent. Because P(B|A) = P(B)")
else:
    print("Events A and B are dependent. Because P(B|A) != P(B)")

Probability of A 0.2325
Probability of B given A 0.6810035842293907
Events A and B are dependent. Because P(B|A) != P(B)

### Probability calculation rules

#### Complement rule

In [12]:
event_A = cupon_purchase[cupon_purchase['coupon_used'] == 'Yes']
n = len(cupon_purchase)

prob_A = len(event_A) / n
prob_not_A = 1 - prob_A

print(f"Probability of event A happening: {prob_A}")
print(f"Probability of event A not happening: {prob_not_A}")

Probability of event A happening: 0.2325
Probability of event A not happening: 0.7675

In [13]:
event_B = cupon_purchase[cupon_purchase['purchased'] == 'Yes']
n = len(cupon_purchase)

prob_B = len(event_B) / n
prob_not_B = 1 - prob_B

print(f"Probability of event B happening: {prob_B} ")
print(f"Probability of event B not happening: {prob_not_B} ")

Probability of event B happening: 0.4116666666666667
Probability of event B not happening: 0.5883333333333334

#### Addition rule

##### General/Dependent multiplication rule

P(A U B)= P(A) + P(B) - P(A ∩ B)

In [14]:
# events
evnt_A = cupon_purchase[cupon_purchase['coupon_used'] == 'Yes']
evnt_B = cupon_purchase[cupon_purchase['purchased'] == 'Yes']
n = len(cupon_purchase)

# events probabilities
prob_A = len(evnt_A) / n
prob_B = len(evnt_B) / n


# intersection events probabilities 
inters_A_B = cupon_purchase[
    (cupon_purchase['coupon_used'] == 'Yes') & 
    (cupon_purchase['purchased'] == 'Yes')
]
inters_events_prob = len(inters_A_B) / n

# union events probabilities
union_events_prob = prob_A + prob_B - inters_events_prob


print(f"Probability of event A happening: {prob_A}")
print(f"Probability of event B happening: {prob_B} ")
print(f"Probability of event A and B happening: {inters_events_prob} ")
print(f"Probability of event A or B happening: {union_events_prob} ")

Probability of event A happening: 0.2325
Probability of event B happening: 0.4116666666666667
Probability of event A and B happening: 0.15833333333333333
Probability of event A or B happening: 0.48583333333333334

##### Mutually exclusive special case

P(A U B) = P(A) + P(B)
- event A: customer is a premium member
- event B: customer is not a premium member

In [15]:
event_A = df[df['premium_member'] == 'Yes']
event_B = df[df['premium_member'] == 'No']
n = len(df)

prob_A = len(event_A) / n
prob_B = len(event_B) / n
union_events_prob = prob_A + prob_B

print(f"Probability of event A happening: {prob_A}")
print(f"Probability of event B happening: {prob_B}")
print(f"Probability of event A or B happening: {union_events_prob}")

Probability of event A happening: 0.3675
Probability of event B happening: 0.6325
Probability of event A or B happening: 1.0

Mutual exclusive events
- A=session came from Organic traffic
- B=session came from Paid Search

In [16]:
event_A = df[df['traffic_source'] == 'Social Media']
event_B = df[df['traffic_source'] == 'Organic']
n = len(df)

prob_A = len(event_A) / n
prob_B = len(event_B) / n
union_events_prob = prob_A + prob_B

print(f"Probability of event A happening: {prob_A}")
print(f"Probability of event B happening: {prob_B}")
print(f"Probability of event A or B happening: {union_events_prob}")

Probability of event A happening: 0.22583333333333333
Probability of event B happening: 0.35583333333333333
Probability of event A or B happening: 0.5816666666666667

#### Multiplication Rule

##### General/Dependent multiplication rule

- Event A - Customers used cupon
- Event B - Customers purchased                                                                             
P(A ∩ B) = P(A) * P(B | A)

In [33]:
(2 / 6) / (3 / 6) * 0.5

0.3333333333333333

In [17]:
# events
event_A = df[df['coupon_used'] == 'Yes']
event_B = df[df['purchased'] == 'Yes']
event_A_and_B = df[
    (df['coupon_used'] == 'Yes') & 
    (df['purchased'] == 'Yes')
]
n = len(df)

# probailities 
prob_A = len(event_A) / n 
prob_B_given_A = len(event_A_and_B) / len(event_A)

intersection_prob_A_and_B = prob_A * prob_B_given_A 

print(f"Probability of customers using a coupon: {prob_A:.4f}")
print(f"Probability of customers purchasing after using coupon: {prob_B_given_A:.4f}")
print(f"Probability of customers using a coupon and purchasing: {intersection_prob_A_and_B:.4f}")

Probability of customers using a coupon: 0.2325
Probability of customers purchasing after using coupon: 0.6810
Probability of customers using a coupon and purchasing: 0.1583

##### Independent-events special case

Independent-events ------ P(A ∩ B) = P(A) * P(B)
- Event A - customer session is from the North region
- Event B - customer is in experiment group A

In [18]:
# events
event_A = df[df['region'] == 'North']
event_B = df[df['experiment_group'] == 'A']
n = len(df)


pron_A = len(event_A) / n
prob_B = len(event_B) / n 

prob_A_and_B = prob_A * prob_B

print(f"probability of customers from North region {prob_A}")
print(f'probability of customers from experiment group A {prob_B}')
print(f"probability of customers from North region and experiement group A {prob_A_and_B}")

probability of customers from North region 0.2325
probability of customers from experiment group A 0.5
probability of customers from North region and experiement group A 0.11625

#### Conditional Probability

- Event A - Customers used cupon
- Event B - Customers purchased

P(A | B) = P( A ∩ B) / P(B)                                                                                                                                           
P(A | B)  means what is the probability of happening event A when event B already happens

In [19]:
event_A = df[df['coupon_used'] == 'Yes']
event_B = df[df['purchased'] == 'Yes']
n = len(df)

event_A_and_B = df[
    (df['coupon_used'] == 'Yes') &
    (df['purchased'] == 'Yes')
]

prob_A_B = len(event_A_and_B) / n 
prob_B = len(event_B) / n
prob_A_given_B = prob_A_B  / prob_B

print(f"Probability of event A and B: {prob_A_and_B}")
print(f"Probability of event B {prob_B}")
print(f"Probability of event A when B is already happened: {prob_A_given_B}")

Probability of event A and B: 0.11625
Probability of event B 0.4116666666666667
Probability of event A when B is already happened: 0.3846153846153846

#### Bayes' Theorem


Bayes' Theorem reverses the direction of probability for example:
Suppose we have `P(B | A)`,                                                                                                                                 
but we want `P(A | B)`,                                                                                                                                             
so Bayes' Theorem: `P(A | B) = P(B | A) * P(A) / P(B)`                                                                                                                          
Probability of A given B not equal to Probability of B given A `P(A | B) ≠ P(B | A)`                                                
- Event A - Customers used cupon
- Event B - Customers purchased

In [20]:
# Events
event_A = df[df["coupon_used"] == "Yes"]
event_B = df[df["purchased"] == "Yes"]

n = len(df)

# Intersection: coupon used AND purchased
event_A_and_B = df[
    (df["coupon_used"] == "Yes") &
    (df["purchased"] == "Yes")
]

# Probabilities
prob_A = len(event_A) / n
prob_B = len(event_B) / n
prob_A_and_B = len(event_A_and_B) / n

# Conditional probability P(B | A)
prob_B_given_A = prob_A_and_B / prob_A

# Bayes' theorem: P(A | B)
prob_A_given_B = (
    prob_B_given_A * prob_A
    / prob_B
)

print(f"Probability of using a coupon, P(A): {prob_A:.4f}")
print(f"Probability of purchasing, P(B): {prob_B:.4f}")
print(f"Probability of coupon usage and purchase, P(A ∩ B): {prob_A_and_B:.4f}")
print(f"Probability of purchasing given coupon usage, P(B | A): {prob_B_given_A:.4f}")
print(f"Probability of coupon usage given purchase, P(A | B): {prob_A_given_B:.4f}")

Probability of using a coupon, P(A): 0.2325
Probability of purchasing, P(B): 0.4117
Probability of coupon usage and purchase, P(A ∩ B): 0.1583
Probability of purchasing given coupon usage, P(B | A): 0.6810
Probability of coupon usage given purchase, P(A | B): 0.3846

In [22]:
2/6

0.3333333333333333

In [23]:
(3 / 6) * (3 / 6)

0.25