In [2]:
import numpy as np
import pandas as pd

from scipy.stats import norm

# Z-test

## One-sample Z-test

Hypotheses:
- H₀: μ = 250
- Hₐ: μ ≠ 250
- population standard deviation: 12

In [3]:
df = pd.read_csv('z_test_data/01_one_sample_z_mean.csv')
df.head()

   cup_id  fill_ml
0       1   251.16
1       2   235.02
2       3   256.51
3       4   258.79
4       5   224.09

In [4]:
# company claims
mu_0 = 250

# known population stadard deviation
sigma = 12

# Significance level
alpha = 0.05

### Two-tailed test

In [5]:
# Sample statistics
sample = df['fill_ml']
# smple length
n = len(sample)
# sample mean
sample_mean = sample.mean()
# standard error 
standard_error = sigma / np.sqrt(n)

print("Sample size:", n)
print("Sample mean:", sample_mean)
print("Standard error:", standard_error)

Sample size: 120
Sample mean: 246.775
Standard error: 1.0954451150103321

In [6]:
# observed Z-statistic
z_observed = (
    sample_mean - mu_0
) /standard_error

print("Observed Z:", z_observed)

Observed Z: -2.9440087465902627

In [7]:
# Critical values 
critical_value = norm.ppf(1 - alpha / 2)
lower_critical = -critical_value
upper_critical = critical_value
print("Critical values:",
      lower_critical,
      upper_critical)

# Decision using critical values
if z_observed < lower_critical or z_observed > upper_critical:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

Critical values: -1.959963984540054 1.959963984540054
Reject H₀ using critical-value method

In [8]:
# P-value
p_value = 2 * norm.sf(abs(z_observed))
print("P-value:", p_value)
print("Alpha:", alpha)

# Dicision using p-value
if p_value < alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

P-value: 0.0032399084308324297
Alpha: 0.05
Reject H₀

### One-tailed test

In [9]:
# Sample statistics
sample = df['fill_ml']
# smple length
n = len(sample)
# sample mean
sample_mean = sample.mean()
# standard error 
standard_error = sigma / np.sqrt(n)

print("Sample size:", n)
print("Sample mean:", sample_mean)
print("Standard error:", standard_error)

Sample size: 120
Sample mean: 246.775
Standard error: 1.0954451150103321

In [10]:
# observed Z-statistic
z_observed = (
    sample_mean - mu_0
) /standard_error

print("Observed Z:", z_observed)

Observed Z: -2.9440087465902627

#### Right-tailed test

In [11]:
# calculating critical value
critical_value = norm.ppf(1 - alpha)
print(f"Critical value (Boundary): {critical_value}")

# Decision using critical values
if z_observed > critical_value:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

Critical value (Boundary): 1.6448536269514722
Fail to reject H₀ using critical-value method

In [12]:
# p-value
p_value = 1 - norm.cdf(z_observed)
print(f"P-value: {p_value}")
print(f"alpha: {alpha}")

# Dicision using p-value
if p_value > alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

P-value: 0.9983800457845838
alpha: 0.05
Reject H₀

#### Left-tailed test

In [13]:
# calculating critical value
critical_value = norm.ppf(alpha)
print(f"Critical value (Boundary): {critical_value}")

# Decision using critical values
if z_observed < critical_value:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

Critical value (Boundary): -1.6448536269514729
Reject H₀

In [14]:
# p-value
p_value = norm.cdf(z_observed)
print(f"P-value: {p_value}")
print(f"alpha: {alpha}")

# Dicision using p-value
if p_value > alpha:
    print("Reject H₀")
else:
    print("Fail to reject H₀")

P-value: 0.0016199542154162149
alpha: 0.05
Fail to reject H₀

## Two-sample Z-test

Samples:
- X̄_A = 72 
- σ_A = 10
- X̄_B = 76
- σ_B = 12    
------------                     
Hypothesis:
- H₀: μ_A = μ_B
- Hₐ: μ_A ≠ μ_B
- Significance level α = 0.05
------------
Formula:
- Z = ((X̄_A - X̄_B) - (μ_A - μ_B)₀) / √((σ_A² / n_A) + (σ_B² / n_B))

In [15]:
df_two_sample = pd.read_csv("z_test_data/02_two_sample_z_mean.csv")
df_two_sample.head()

   customer_id group  satisfaction_score
0            1     A               61.77
1            2     A               73.79
2            3     A               74.20
3            4     A               85.59
4            5     A               80.35

In [16]:
df_two_sample['group'].value_counts()

group
A    100
B    100
Name: count, dtype: int64

In [20]:
# sample A 
mu_A = 72
sample_A_std = 10

# sample B 
sample_B_std = 12
mu_B = 76

# Significance level 
alpha = 0.05

In [21]:
# sample A 
sample_A = df_two_sample[df_two_sample['group'] == 'A']['satisfaction_score']
sample_A_n = len(sample_A)
sample_A_mean = sample_A.mean()
print("Sample A mean: ", sample_A_mean)

# Sample B
sample_B = df_two_sample[df_two_sample['group'] == 'B']['satisfaction_score']
sample_B_mean = sample_B.mean()
sample_B_n = len(sample_B)
print("Sample B mean: ", sample_B_mean)

Sample A mean:  71.90969999999999
Sample B mean:  74.2679

In [27]:
# Two-sample-Z-statistic calculation: Z = ((X̄_A - X̄_B) - (μ_A - μ_B)₀) / √((σ_A² / n_A) + (σ_B² / n_B))
hypothesis_difference = 0
two_sample_Z_test = (
    ((sample_A_mean - sample_B_mean) - hypothesis_difference)
    /
    np.sqrt(
        (sample_A_std ** 2 / sample_A_n) 
        + 
        (sample_B_std ** 2 / sample_B_n)
    )
)

print("Test Statistic Value", two_sample_Z_test)

Test Statistic Value -1.5096828512887834

### Two-tailed Hypothesis

In [28]:
# Critical values
critical_value = norm.ppf(1 - alpha / 2)
upper_critical = critical_value
lower_critical = -critical_value
print(
    "Critical-values:", 
    lower_critical,
    upper_critical
)

# making decision by critical values
if lower_critical < two_sample_Z_test or two_sample_Z_test > upper_critical:
    print("Failed to reject Null Hypothesis")
else:
    print("Reject Null Hypothesis")

Critical-values: -1.959963984540054 1.959963984540054
Failed to reject Null Hypothesis

In [26]:
# P-value
p_value = 2 * (1 - norm.cdf(abs(two_sample_Z_test)))
print("P-value: ", p_value)
print("Alpha: ", alpha)

# making decision by p-value
if p_value < alpha:
    print("Reject Null Hypothesis")
else:
    print("Fail to reject Null Hypothesis")

P-value:  0.29323344610547997
Alpha:  0.05
Fail to reject Null Hypothesis

### One-tailed test

#### Right-tailed test

In [30]:
# critical value
critical_value = norm.ppf(1 - alpha)
print("critical_value: ", critical_value)

# Decision using critical values
if two_sample_Z_test > critical_value:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

critical_value:  1.6448536269514722
Fail to reject H₀ using critical-value method

In [33]:
# P-value
p_value = 1 - norm.cdf(two_sample_Z_test)
print("p_value: ", p_value)
print("alpha: ", alpha)

if p_value < alpha:
    print("Rject H₀")
else:
    print("Fail to reject H₀")

p_value:  0.9344378154531684
alpha:  0.05
Fail to reject H₀

#### Left-tailed test

In [34]:
# critical value
critical_value = norm.ppf(alpha)
print("critical_value: ", critical_value)

# Decision using critical values
if two_sample_Z_test < critical_value:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

critical_value:  -1.6448536269514729
Fail to reject H₀ using critical-value method

In [36]:
# P-value
p_value = norm.cdf(two_sample_Z_test)
print("p_value: ", p_value)
print("alpha: ", alpha)

if p_value < alpha:
    print("Rject H₀")
else:
    print("Fail to reject H₀")

p_value:  0.0655621845468316
alpha:  0.05
Fail to reject H₀

## One-Proportion Z-test

Hypotheses:
- H₀: p = 0.30
- Hₐ: p ≠ 0.30

In [41]:
df = pd.read_csv("z_test_data/03_one_proportion_z.csv")
df.head()

   visitor_id  purchased
0           1          1
1           2          1
2           3          0
3           4          0
4           5          0

In [40]:
df.shape

(300, 2)

In [42]:
# population mean purchase rate
pop_p = 0.30

# significance level alpga 
alpha = 0.05

### Two-taile test

In [45]:
# sample 
sample = df['purchased']
# sample length 
n = len(df)
# sample mean
sample_p = sample.sum() / n

print("Sample length: ", n)
print("Sample Mean: ", sample_p)

Sample length:  300
Sample Mean:  0.38666666666666666

In [46]:
# observed Z-statistic Z = (p̂ - p₀) / √((p₀(1 - p₀)) / n)
z_observed = (sample_p - pop_p) / np.sqrt((pop_p * (1 - pop_p) / n))
print("Observed Z-statistc value: ", z_observed)

Observed Z-statistc value:  3.2756920994133027

In [47]:
# Critical Values 
critical_value = norm.ppf(1 - alpha / 2)
lower_critical = -critical_value
upper_critical = critical_value

print("Critical Values: ", lower_critical, upper_critical)

# Decision using Critical values
if z_observed < lower_critical or z_observed > upper_critical:
    print("Reject H₀ using critical-value method")
else:
    print("Fail to reject H₀ using critical-value method")

Critical Values:  -1.959963984540054 1.959963984540054
Reject H₀ using critical-value method

In [48]:
# P-value
p_value = 2 * (1 - norm.cdf(abs(z_observed)))
print("P-value: ", p_value)
print("Alpha: ", alpha)

# Decision using p-value
if p_value < alpha:
    print("Rject H₀")
else:
    print("Fail to reject H₀")

P-value:  0.0010540340457847464
Alpha:  0.05
Rject H₀