In [ ]:
import pandas as pd
import numpy as np

In [76]:
df = pd.read_csv('data.csv')
df.head()

,session_id,region,age_group,traffic_source,experiment_group,premium_member,used_mobile_app,ad_clicked,email_opened,coupon_used,visit_count_30d,engagement_level,purchased,payment_method,order_value_usd,returned_order,support_contacted,churned,fraudulent_transaction,fraud_alert
0,S0001,North,18-24,Social Media,A,Yes,Yes,No,No,Yes,4,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
1,S0002,West,45+,Organic,A,No,No,No,No,No,0,Low,No,NaN,0.0,Not Applicable,No,Yes,No,No
2,S0003,East,35-44,Organic,A,No,Yes,No,No,No,4,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
3,S0004,East,35-44,Paid Search,A,Yes,Yes,No,No,No,5,Medium,No,NaN,0.0,Not Applicable,No,No,No,No
4,S0005,East,35-44,Organic,B,Yes,No,Yes,No,Yes,5,Medium,No,NaN,0.0,Not Applicable,No,No,No,No

In [77]:
2 * 3 + 4 * 5 + 10

36

# First Combination

X = number of visits a randomly selected customers made in the last 30 days

In [78]:
visits_30d = df['visit_count_30d']

visits_30d.unique()

array([ 4,  0,  5,  3,  2,  1,  8,  6,  7, 10,  9, 13, 11, 14, 12])

## Expected Value

In [79]:
visit_frequency = visits_30d.value_counts().sort_values()
visit_frequency

visit_count_30d
14      1
13      2
12      2
11      4
10     17
9      25
8      53
0      59
7      61
6     100
5     126
1     149
4     176
2     202
3     223
Name: count, dtype: int64

In [80]:
visit_probability = visit_frequency / len(df) 
visit_probability

visit_count_30d
14    0.000833
13    0.001667
12    0.001667
11    0.003333
10    0.014167
9     0.020833
8     0.044167
0     0.049167
7     0.050833
6     0.083333
5     0.105000
1     0.124167
4     0.146667
2     0.168333
3     0.185833
Name: count, dtype: float64

In [81]:
expected_visit = np.sum(visit_frequency.index * visit_probability.values)
expected_visit

np.float64(3.7583333333333337)

In [82]:
df['visit_count_30d'].mean()

np.float64(3.7583333333333333)

In [83]:
visits_results = pd.DataFrame(
    {
        "value":visit_frequency.index,
        "probability":visit_probability.values
    }
)
visits_results

    value  probability
0      14     0.000833
1      13     0.001667
2      12     0.001667
3      11     0.003333
4      10     0.014167
5       9     0.020833
6       8     0.044167
7       0     0.049167
8       7     0.050833
9       6     0.083333
10      5     0.105000
11      1     0.124167
12      4     0.146667
13      2     0.168333
14      3     0.185833

## Expected Value of Transformation

Y = g(X)
- E[Y] = E[g(X)]
- g(X) = X²

In [84]:
visits_results

    value  probability
0      14     0.000833
1      13     0.001667
2      12     0.001667
3      11     0.003333
4      10     0.014167
5       9     0.020833
6       8     0.044167
7       0     0.049167
8       7     0.050833
9       6     0.083333
10      5     0.105000
11      1     0.124167
12      4     0.146667
13      2     0.168333
14      3     0.185833

In [85]:
visits_results['transformation'] = visits_results['value'] ** 2
visits_results

    value  probability  transformation
0      14     0.000833             196
1      13     0.001667             169
2      12     0.001667             144
3      11     0.003333             121
4      10     0.014167             100
5       9     0.020833              81
6       8     0.044167              64
7       0     0.049167               0
8       7     0.050833              49
9       6     0.083333              36
10      5     0.105000              25
11      1     0.124167               1
12      4     0.146667              16
13      2     0.168333               4
14      3     0.185833               9

Expected Value of Y

In [86]:
# expected value of Y 
expected_value_Y = np.sum(visits_results['transformation'] * visits_results['probability'])
expected_value_Y

np.float64(19.951666666666664)

E[Y] ≠ g(E[X])

In [87]:
expected_visit

np.float64(3.7583333333333337)

In [88]:
expected_value_Y2 = expected_visit **2 
expected_value_Y2

np.float64(14.125069444444447)

## Properties of expected value

### 1-Property: Multiplying a random variable by a constant

`E[cX] = cE[X]`
- Suppose Y = 2X

In [89]:
expected_visit

np.float64(3.7583333333333337)

In [90]:
visits_results

    value  probability  transformation
0      14     0.000833             196
1      13     0.001667             169
2      12     0.001667             144
3      11     0.003333             121
4      10     0.014167             100
5       9     0.020833              81
6       8     0.044167              64
7       0     0.049167               0
8       7     0.050833              49
9       6     0.083333              36
10      5     0.105000              25
11      1     0.124167               1
12      4     0.146667              16
13      2     0.168333               4
14      3     0.185833               9

In [91]:
visits_results['2X'] = visits_results['value'] * 2
visits_results

    value  probability  transformation  2X
0      14     0.000833             196  28
1      13     0.001667             169  26
2      12     0.001667             144  24
3      11     0.003333             121  22
4      10     0.014167             100  20
5       9     0.020833              81  18
6       8     0.044167              64  16
7       0     0.049167               0   0
8       7     0.050833              49  14
9       6     0.083333              36  12
10      5     0.105000              25  10
11      1     0.124167               1   2
12      4     0.146667              16   8
13      2     0.168333               4   4
14      3     0.185833               9   6

In [92]:
expected_visit * 2

np.float64(7.5166666666666675)

In [93]:
np.sum(visits_results['2X'] * visits_results['probability'])

np.float64(7.5166666666666675)

### 2-Property: Adding a constant

`E[X + c] = E[X] + c`
- Y = X + 10

In [94]:
visits_results['X+10'] = visits_results['value'] + 10
visits_results

    value  probability  transformation  2X  X+10
0      14     0.000833             196  28    24
1      13     0.001667             169  26    23
2      12     0.001667             144  24    22
3      11     0.003333             121  22    21
4      10     0.014167             100  20    20
5       9     0.020833              81  18    19
6       8     0.044167              64  16    18
7       0     0.049167               0   0    10
8       7     0.050833              49  14    17
9       6     0.083333              36  12    16
10      5     0.105000              25  10    15
11      1     0.124167               1   2    11
12      4     0.146667              16   8    14
13      2     0.168333               4   4    12
14      3     0.185833               9   6    13

In [95]:
expected_visit

np.float64(3.7583333333333337)

In [96]:
expected_visit + 10

np.float64(13.758333333333333)

In [97]:
np.sum(visits_results['probability'] * visits_results['X+10'])

np.float64(13.758333333333333)

### 3-Property: General Linear Transformation

`E[Y] = E[aX + b] = aE[X] + b`
- E[X] = 4
- a = 2
- b = 5

In [98]:
visits_results

    value  probability  transformation  2X  X+10
0      14     0.000833             196  28    24
1      13     0.001667             169  26    23
2      12     0.001667             144  24    22
3      11     0.003333             121  22    21
4      10     0.014167             100  20    20
5       9     0.020833              81  18    19
6       8     0.044167              64  16    18
7       0     0.049167               0   0    10
8       7     0.050833              49  14    17
9       6     0.083333              36  12    16
10      5     0.105000              25  10    15
11      1     0.124167               1   2    11
12      4     0.146667              16   8    14
13      2     0.168333               4   4    12
14      3     0.185833               9   6    13

In [99]:
a = 2
b = 5
visits_results['aX+b'] = a * visits_results['value'] + b
visits_results

    value  probability  transformation  2X  X+10  aX+b
0      14     0.000833             196  28    24    33
1      13     0.001667             169  26    23    31
2      12     0.001667             144  24    22    29
3      11     0.003333             121  22    21    27
4      10     0.014167             100  20    20    25
5       9     0.020833              81  18    19    23
6       8     0.044167              64  16    18    21
7       0     0.049167               0   0    10     5
8       7     0.050833              49  14    17    19
9       6     0.083333              36  12    16    17
10      5     0.105000              25  10    15    15
11      1     0.124167               1   2    11     7
12      4     0.146667              16   8    14    13
13      2     0.168333               4   4    12     9
14      3     0.185833               9   6    13    11

In [100]:
a * expected_visit + b

np.float64(12.516666666666667)

In [101]:
np.sum(visits_results['probability'] * visits_results['aX+b'])

np.float64(12.51666666666667)

### 4-Propery: Expected value of s sum

`E[X + Y] = E[X] + E[Y]`
- X = premium members visits count
- Y = not premium members visits count
- Z = total visits

In [102]:
X = df.loc[
    df['premium_member'] == 'Yes',
    'visit_count_30d'
]

Y = df.loc[
    df['premium_member'] == 'No',
    'visit_count_30d'
]

In [103]:
X_frequency = X.value_counts().sort_values()
X_probability = X_frequency / len(df)
expected_value_X = np.sum(X_frequency.index * X_probability.values)
expected_value_X

np.float64(1.9758333333333333)

In [104]:
Y_frequency = Y.value_counts().sort_values()
Y_probability = Y_frequency / len(df)
expected_value_Y = np.sum(Y_frequency.index * Y_probability.values)
expected_value_Y

np.float64(1.7825)

In [105]:
total_visits = expected_value_X + expected_value_Y
total_visits

np.float64(3.7583333333333333)

### 5-Property: General linearity of expectation

`E[aX + bY + c] = aE[X] + bE[Y] + c`
- X = premium members visits count
- Y = not premium members visits count
- a = 2
- b = 4
- c = 10
- `Z` = a * E[X] + b * E[Y] + c

In [106]:
expected_value_X

np.float64(1.9758333333333333)

In [107]:
expected_value_Y

np.float64(1.7825)

In [108]:
a = 2
b = 4
c = 10

In [109]:
z = a * expected_value_X + b * expected_value_Y + 10
z

np.float64(21.081666666666667)

### 6-Property: Multiplication

- if X and Y are independent `E[XY] = E[X]E[Y]`
- if X and Y are dependent `E[XY] ≠ E[X] * E[Y]`
----
- X = visits count of premium users in last 30 days
- Y = visits count of non-premium users in last 30 days

They are `dependet` varianles

In [110]:
X = np.where(
    df["premium_member"] == "Yes",
    df["visit_count_30d"],
    0
)

Y = np.where(
    df["premium_member"] == "No",
    df["visit_count_30d"],
    0
)

In [111]:
visits_prem_vs_nonprem = pd.DataFrame({
    "premium_visits":X,
    "non_premium_visits":Y
})
visits_prem_vs_nonprem.head()

   premium_visits  non_premium_visits
0               4                   0
1               0                   0
2               0                   4
3               5                   0
4               5                   0

In [112]:
visits_prem_vs_nonprem['multiplication'] = visits_prem_vs_nonprem['premium_visits'] * visits_prem_vs_nonprem['non_premium_visits']
visits_prem_vs_nonprem.head()

   premium_visits  non_premium_visits  multiplication
0               4                   0               0
1               0                   0               0
2               0                   4               0
3               5                   0               0
4               5                   0               0

In [113]:
X_freq = visits_prem_vs_nonprem['premium_visits'].value_counts()
X_prob = X_freq / len(df)
X_expected_value = np.sum(X_freq.index * X_prob.values)
X_expected_value

np.float64(1.9758333333333336)

In [114]:
Y_freq = visits_prem_vs_nonprem['non_premium_visits'].value_counts()
Y_prob = Y_freq / len(df)
Y_expected_value = np.sum(Y_freq.index * Y_prob.values)
Y_expected_value

np.float64(1.7824999999999998)

In [115]:
XY_freq = visits_prem_vs_nonprem['multiplication'].value_counts()
XY_prob = XY_freq / len(df)
XY_expected_value = np.sum(XY_freq.index * XY_prob.values)
XY_expected_value

np.float64(0.0)

In [116]:
X_expected_value * Y_expected_value

np.float64(3.5219229166666666)

## Variance

In [117]:
visits_results

    value  probability  transformation  2X  X+10  aX+b
0      14     0.000833             196  28    24    33
1      13     0.001667             169  26    23    31
2      12     0.001667             144  24    22    29
3      11     0.003333             121  22    21    27
4      10     0.014167             100  20    20    25
5       9     0.020833              81  18    19    23
6       8     0.044167              64  16    18    21
7       0     0.049167               0   0    10     5
8       7     0.050833              49  14    17    19
9       6     0.083333              36  12    16    17
10      5     0.105000              25  10    15    15
11      1     0.124167               1   2    11     7
12      4     0.146667              16   8    14    13
13      2     0.168333               4   4    12     9
14      3     0.185833               9   6    13    11

In [118]:
visits_results['squared_diviations'] = (visits_results['value'] - expected_visit) ** 2 
visits_results

    value  probability  transformation  2X  X+10  aX+b  squared_diviations
0      14     0.000833             196  28    24    33          104.891736
1      13     0.001667             169  26    23    31           85.408403
2      12     0.001667             144  24    22    29           67.925069
3      11     0.003333             121  22    21    27           52.441736
4      10     0.014167             100  20    20    25           38.958403
5       9     0.020833              81  18    19    23           27.475069
6       8     0.044167              64  16    18    21           17.991736
7       0     0.049167               0   0    10     5           14.125069
8       7     0.050833              49  14    17    19           10.508403
9       6     0.083333              36  12    16    17            5.025069
10      5     0.105000              25  10    15    15            1.541736
11      1     0.124167               1   2    11     7            7.608403
12      4     0.146667              16   8    14    13            0.058403
13      2     0.168333               4   4    12     9            3.091736
14      3     0.185833               9   6    13    11            0.575069

In [119]:
visits_variance = np.sum(visits_results['squared_diviations'] * visits_results['probability'])
visits_variance

np.float64(5.826597222222221)

## Standard Deviation

In [120]:
visits_standard_deviation = np.sqrt(visits_variance)
visits_standard_deviation

np.float64(2.4138345474000946)

## Covariance

What is the coveriance `Cov(X, Y) = E[(X - E[X]) * (Y - E[Y])]`
- X = visits 
- Y = 2X

In [121]:
visits_results

    value  probability  transformation  2X  X+10  aX+b  squared_diviations
0      14     0.000833             196  28    24    33          104.891736
1      13     0.001667             169  26    23    31           85.408403
2      12     0.001667             144  24    22    29           67.925069
3      11     0.003333             121  22    21    27           52.441736
4      10     0.014167             100  20    20    25           38.958403
5       9     0.020833              81  18    19    23           27.475069
6       8     0.044167              64  16    18    21           17.991736
7       0     0.049167               0   0    10     5           14.125069
8       7     0.050833              49  14    17    19           10.508403
9       6     0.083333              36  12    16    17            5.025069
10      5     0.105000              25  10    15    15            1.541736
11      1     0.124167               1   2    11     7            7.608403
12      4     0.146667              16   8    14    13            0.058403
13      2     0.168333               4   4    12     9            3.091736
14      3     0.185833               9   6    13    11            0.575069

In [123]:
expected_visit

np.float64(3.7583333333333337)

In [125]:
expected_visit_of_2X = np.sum(visits_results['2X'] * visits_results['probability'])
expected_visit_of_2X

np.float64(7.5166666666666675)

In [126]:
visits_results['(X-E[X])*(Y-E[Y])'] = (visits_results['value'] - expected_visit) * (visits_results['2X'] - expected_visit_of_2X)
visits_results

,value,probability,transformation,2X,X+10,aX+b,squared_diviations,(X-E[X])*(Y-E[Y])
0,14,0.000833,196,28,24,33,104.891736,209.783472
1,13,0.001667,169,26,23,31,85.408403,170.816806
2,12,0.001667,144,24,22,29,67.925069,135.850139
3,11,0.003333,121,22,21,27,52.441736,104.883472
4,10,0.014167,100,20,20,25,38.958403,77.916806
5,9,0.020833,81,18,19,23,27.475069,54.950139
6,8,0.044167,64,16,18,21,17.991736,35.983472
7,0,0.049167,0,0,10,5,14.125069,28.250139
8,7,0.050833,49,14,17,19,10.508403,21.016806
9,6,0.083333,36,12,16,17,5.025069,10.050139
10,5,0.105000,25,10,15,15,1.541736,3.083472
11,1,0.124167,1,2,11,7,7.608403,15.216806
12,4,0.146667,16,8,14,13,0.058403,0.116806
13,2,0.168333,4,4,12,9,3.091736,6.183472
14,3,0.185833,9,6,13,11,0.575069,1.150139

In [127]:
coveriance_X_Y = np.sum(visits_results['probability'] * visits_results['(X-E[X])*(Y-E[Y])'])
coveriance_X_Y

np.float64(11.653194444444441)