In [30]:
import pandas as pd
import numpy as np

from sklearn.model_selection import GroupShuffleSplit

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [4]:
df = pd.read_csv("data/datav3.csv")
df.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [5]:
df.shape

(7519, 29)

# Assumptions

## Independence of Observations

### Repeated entities and Duplicated IDs

#### Duplicated IDs

In [6]:
df.duplicated().sum()

np.int64(35)

In [7]:
pd.set_option('display.max_rows', None)

In [8]:
exact_duplicates = df[df.duplicated(keep=False)]
exact_duplicates.sort_values(['customer_id', 'observation_month']).head(20)

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
5077,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
6080,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
731,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
999,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
5180,CUST00634,2026-01-01,B04,49,5360.73,64293.39,3,7,4.85,13.97,1,1,24.1,2,9,3,1,6,19,Mobile,Central,Dark,Master,Affiliate,CMP01,0.5543,0.4336,0,0
5830,CUST00634,2026-01-01,B04,49,5360.73,64293.39,3,7,4.85,13.97,1,1,24.1,2,9,3,1,6,19,Mobile,Central,Dark,Master,Affiliate,CMP01,0.5543,0.4336,0,0
2884,CUST00639,2026-01-01,B14,36,3496.38,42021.33,7,22,26.89,21.72,0,0,27.7,3,4,4,1,5,14,Mobile,North,Dark,High School,Referral,CMP01,-0.0494,0.0916,0,0
6333,CUST00639,2026-01-01,B14,36,3496.38,42021.33,7,22,26.89,21.72,0,0,27.7,3,4,4,1,5,14,Mobile,North,Dark,High School,Referral,CMP01,-0.0494,0.0916,0,0
1601,CUST00887,2026-02-01,B15,38,4849.39,58041.66,10,30,20.81,21.70,1,0,32.0,1,9,6,1,6,19,Mobile,North,Dark,Bachelor,Social,CMP02,0.5303,-0.0009,0,0
6975,CUST00887,2026-02-01,B15,38,4849.39,58041.66,10,30,20.81,21.70,1,0,32.0,1,9,6,1,6,19,Mobile,North,Dark,Bachelor,Social,CMP02,0.5303,-0.0009,0,0
3596,CUST01020,2025-04-01,B10,51,6311.86,76053.13,8,31,23.31,13.21,2,1,27.8,1,8,5,3,7,21,Desktop,East,Dark,Master,Search,CMP07,0.7241,-0.7363,0,0
4911,CUST01020,2025-04-01,B10,51,6311.86,76053.13,8,31,23.31,13.21,2,1,27.8,1,8,5,3,7,21,Desktop,East,Dark,Master,Search,CMP07,0.7241,-0.7363,0,0
2183,CUST01286,2025-01-01,B14,36,4039.88,48510.99,7,23,18.18,26.55,1,1,17.9,5,8,8,1,7,10,Tablet,North,System,Bachelor,Email,CMP60,0.1843,0.7257,0,0
5702,CUST01286,2025-01-01,B14,36,4039.88,48510.99,7,23,18.18,26.55,1,1,17.9,5,8,8,1,7,10,Tablet,North,System,Bachelor,Email,CMP60,0.1843,0.7257,0,0
3839,CUST01321,2025-08-01,B19,24,6345.16,76806.98,8,25,21.06,11.80,2,0,3.7,3,10,7,1,7,12,Mobile,South,Dark,Master,Social,CMP02,0.0926,-0.2380,1,0
6340,CUST01321,2025-08-01,B19,24,6345.16,76806.98,8,25,21.06,11.80,2,0,3.7,3,10,7,1,7,12,Mobile,South,Dark,Master,Social,CMP02,0.0926,-0.2380,1,0
1072,CUST01372,2025-10-01,B18,34,5263.53,63459.71,9,31,36.12,20.09,1,1,37.5,2,12,3,3,3,7,Desktop,South,Light,High School,Organic,CMP01,-0.9548,0.1328,1,0
3454,CUST01372,2025-10-01,B18,34,5263.53,63459.71,9,31,36.12,20.09,1,1,37.5,2,12,3,3,3,7,Desktop,South,Light,High School,Organic,CMP01,-0.9548,0.1328,1,0
2615,CUST01396,2025-08-01,B12,41,6756.68,81219.61,7,25,24.13,15.92,1,1,72.2,2,13,7,0,4,17,Tablet,North,Light,Master,Social,CMP01,-1.7677,-0.6401,0,0
6789,CUST01396,2025-08-01,B12,41,6756.68,81219.61,7,25,24.13,15.92,1,1,72.2,2,13,7,0,4,17,Tablet,North,Light,Master,Social,CMP01,-1.7677,-0.6401,0,0

they are exact duplicated columns, I will drop them

In [9]:
df_clean = df.drop_duplicates()

In [10]:
df_clean.shape

(7484, 29)

#### Repeated entities

In [11]:
customer_counts = df_clean['customer_id'].value_counts()
customer_counts.head()

customer_id
CUST03090    3
CUST02133    3
CUST01676    3
CUST03203    3
CUST02897    3
Name: count, dtype: int64

In [12]:
repeated_customers = customer_counts[customer_counts > 1]
len(repeated_customers)

1775

In [13]:
pd.set_option('display.max_rows', None)

In [14]:
repeated_customers_df =  df_clean[df_clean['customer_id'].isin(repeated_customers.index)].sort_values(by='customer_id')
repeated_customers_df.head(10)

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
630,CUST00001,2025-12-01,B17,40,14331.28,172408.24,6,21,32.13,10.34,1,0,8.2,2,12,4,1,5,8,Mobile,South,Dark,Master,Search,CMP01,0.4028,-0.3411,1,0
4953,CUST00001,2025-11-01,B17,40,14525.17,173291.39,9,31,23.24,10.14,1,0,47.9,1,13,4,3,7,18,Mobile,South,Dark,Master,Partner_Rare,CMP02,1.4404,0.7305,1,0
4195,CUST00003,2026-04-01,B15,31,2283.80,27365.68,7,24,31.83,11.54,1,0,44.1,2,9,6,1,6,11,Mobile,North,Light,High School,Social,CMP06,2.5045,-0.0049,0,0
6624,CUST00003,2026-05-01,B15,31,2359.29,28074.30,7,23,33.04,7.09,2,0,50.2,0,5,3,0,5,19,Mobile,North,Light,High School,Search,CMP01,-0.2593,-0.6711,1,0
3236,CUST00004,2026-02-01,B15,27,4735.69,56815.43,9,33,43.15,23.18,0,0,15.4,3,13,8,1,6,11,Mobile,North,Dark,Bachelor,Referral,CMP01,1.1225,-0.0007,0,0
5128,CUST00004,2026-03-01,B15,27,4576.81,54304.18,6,22,17.01,16.45,1,0,19.2,2,3,2,1,7,8,Mobile,North,Dark,Bachelor,Search,CMP33,0.7423,0.2380,0,0
7101,CUST00006,2025-06-01,B10,40,6764.86,80682.02,11,33,25.74,28.96,1,0,25.9,4,10,4,3,9,9,Desktop,East,Light,Bachelor,Social,CMP01,0.5939,0.2385,1,0
2215,CUST00006,2025-07-01,B10,40,6702.88,80338.78,8,31,25.39,27.59,0,0,35.9,4,12,4,0,3,12,Desktop,East,Light,Bachelor,Social,CMP03,-0.9011,-0.9781,0,0
3514,CUST00006,2025-05-01,B10,40,6758.65,81038.19,12,39,30.81,7.78,0,0,45.7,2,16,5,0,7,21,Desktop,East,Light,Bachelor,Search,CMP02,-0.4524,0.1382,0,0
1474,CUST00007,2026-02-01,B14,36,4494.10,54132.37,10,32,29.26,2.86,0,0,6.6,2,9,6,0,5,13,Mobile,North,Light,PhD,Affiliate,CMP08,-0.1623,0.3194,0,0

In [15]:
customer_counts.value_counts().sort_values()

count
3     509
2    1266
1    3425
Name: count, dtype: int64

In [16]:
df_clean[
    df_clean['customer_id'] == 'CUST00006'
][
    [
        'customer_id',
        'observation_month',
        'monthly_income',
        'purchased'
    ]
].sort_values('observation_month')

     customer_id observation_month  monthly_income  purchased
3514   CUST00006        2025-05-01         6758.65          0
7101   CUST00006        2025-06-01         6764.86          0
2215   CUST00006        2025-07-01         6702.88          0

they are not duplicated rows, they are legitimate repeated measurements.Same customers with different time points.                                         
Treatments:
- `Agrregation` if data has multiple lower-level rows, but we want unit of analysis should be higher-level.
- `Group-aware train/test splitting`

##### Aggregation

In [17]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [22]:
yearly_df = df_clean.copy()

yearly_df['observation_month'] = pd.to_datetime(yearly_df['observation_month'])
yearly_df['year'] = yearly_df['observation_month'].dt.year
yearly_df.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased,year
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0,2026
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0,2025
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0,2026
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0,2025
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0,2025

In [25]:
customer_year_df = (
    yearly_df.groupby(
        ['customer_id', 'year']
    )
    .agg(
        monthly_income=('monthly_income', 'mean'),
        annual_income=('annual_income', 'mean'),

        website_visits_30d=('website_visits_30d', 'sum'),
        website_visits_90d=('website_visits_90d', 'sum'),

        session_minutes=('session_minutes', 'sum'),

        discount_pct=('discount_pct', 'mean'),

        support_tickets_30d=('support_tickets_30d', 'sum'),

        days_since_last_purchase=(
            'days_since_last_purchase',
            'last'
        ),

        cart_items=('cart_items', 'sum'),

        email_opens_30d=('email_opens_30d', 'sum'),

        profile_views_30d=(
            'profile_views_30d',
            'sum'
        ),

        social_referrals_30d=(
            'social_referrals_30d',
            'sum'
        ),

        survey_score=('survey_score', 'mean'),

        purchased=('purchased', 'max')
    )
    .reset_index()
)

In [26]:
customer_year_df.head()

,customer_id,year,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,purchased
0,CUST00001,2025,14428.225,172849.815,15,52,55.37,10.240,2,47.9,3,25,8,4,6.0,0
1,CUST00002,2025,4940.630,59718.200,6,23,20.98,22.280,0,26.6,0,4,1,2,4.0,1
2,CUST00003,2026,2321.545,27719.990,14,47,64.87,9.315,3,50.2,2,14,9,1,5.5,0
3,CUST00004,2026,4656.250,55559.805,15,55,60.16,19.815,1,19.2,5,16,10,2,6.5,0
4,CUST00005,2025,4199.810,50368.140,12,40,15.96,12.420,0,60.0,3,17,9,1,5.0,0

##### Group-aware train-test split

In [28]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [31]:
X = df_clean.drop(columns=['purchased'])
y = df_clean['purchased']

groups = df_clean['customer_id']

gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.2,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(X, y, groups=groups)
)


X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

In [32]:
X_train.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1
6,CUST03223,2026-02-01,B11,34,3717.06,44096.22,12,36,26.89,16.75,1,1,17.3,4,5,9,1,6,20,Mobile,North,Dark,Bachelor,Social,CMP01,1.1912,-0.4454,0

In [33]:
train_customers = set(df_clean.iloc[train_idx]['customer_id'])
test_customers = set(df_clean.iloc[test_idx]['customer_id'])

overlap = train_customers.intersection(test_customers)

print(overlap)

set()

### Natural groups or clusters

In [34]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

`1. Does the dataset have a meaningful grouping structure ?`

In [45]:
df_clean['branch_id'].nunique()

25

In [42]:
df_clean['branch_id'].value_counts().sort_values()

branch_id
B01    235
B05    252
B03    259
B15    264
B04    265
B02    268
B23    280
B25    282
B12    283
B22    293
B24    294
B09    296
B10    297
B14    297
B13    298
B11    302
B21    313
B08    316
B16    321
B19    321
B07    326
B17    343
B18    350
B06    353
B20    376
Name: count, dtype: int64

In [41]:
# number of unique customers in each branch
df.groupby('branch_id')['customer_id'].nunique().sort_values()

branch_id
B01    158
B04    173
B05    174
B03    177
B02    179
B15    189
B25    194
B23    196
B12    199
B10    203
B14    203
B11    203
B24    204
B22    210
B13    211
B09    211
B07    218
B19    219
B08    226
B21    227
B16    231
B06    241
B18    245
B17    247
B20    262
Name: customer_id, dtype: int64

the dataset has a meaningful grouping structure because multiple different customers belong to the same branch.

`2. Are observations within a group more similar than observations across groups?`

In [54]:
branch_summary = (
    df.groupby('branch_id')
      .agg(
          customers=('customer_id', 'nunique'),
          observations=('customer_id', 'size'),
          purchase_rate=('purchased', 'mean')
      )
)

branch_summary.sort_values(by='purchase_rate')

           customers  observations  purchase_rate
branch_id
B11              203           303       0.075908
B17              247           344       0.110465
B14              203           299       0.120401
B09              211           298       0.120805
B18              245           352       0.122159
B10              203           299       0.127090
B15              189           267       0.127341
B12              199           284       0.130282
B04              173           267       0.138577
B02              179           269       0.141264
B08              226           318       0.141509
B24              204           294       0.142857
B21              227           313       0.143770
B13              211           301       0.146179
B23              196           281       0.149466
B16              231           321       0.149533
B25              194           282       0.152482
B20              262           379       0.153034
B06              241           355       0.154930
B03              177           261       0.160920
B01              158           235       0.161702
B22              210           295       0.162712
B05              174           253       0.177866
B19              219           323       0.182663
B07              218           326       0.236196

In [52]:
overall_purchase_rate = df['purchased'].mean()

overall_purchase_rate

np.float64(0.14509908232477722)

In [53]:
branch_rates = (
    df.groupby('branch_id')['purchased']
      .mean()
)

print("Min:", branch_rates.min())
print("Max:", branch_rates.max())
print("Std:", branch_rates.std())

Min: 0.07590759075907591
Max: 0.2361963190184049
Std: 0.029242373704262154

In [65]:
braches_stats = df_clean.groupby('branch_id')[
    ['age',
    'monthly_income', 
    'annual_income', 
    'website_visits_30d',
    'website_visits_90d', 
    'session_minutes', 
    'discount_pct',
    'support_tickets_30d', 
    'premium_member', 
    'days_since_last_purchase',
    'cart_items', 
    'email_opens_30d', 
    'profile_views_30d',
    'social_referrals_30d', 
    'survey_score', 
    'preferred_contact_hour',
    'noise_feature_1',
    'noise_feature_2', 
    'noise_feature_3', 
    'purchased']
].mean()

In [66]:
df_stats = df_clean[
    [
        'age',
        'monthly_income', 
        'annual_income', 
        'website_visits_30d',
        'website_visits_90d', 
        'session_minutes', 
        'discount_pct',
        'support_tickets_30d', 
        'premium_member', 
        'days_since_last_purchase',
        'cart_items', 
        'email_opens_30d', 
        'profile_views_30d',
        'social_referrals_30d', 
        'survey_score', 
        'preferred_contact_hour',
        'noise_feature_1',
        'noise_feature_2', 
        'noise_feature_3', 
        'purchased'
    ]
].mean()

In [63]:
comparison_df = braches_stats.copy()
comparison_df.loc['overall_data'] = df_stats

In [64]:
comparison_df

,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,noise_feature_1,noise_feature_2,noise_feature_3,purchased
branch_id,,,,,,,,,,,,,,,,,,,,
B01,39.855319,5153.626213,61882.214298,7.851064,27.008511,21.443617,15.244638,0.731915,0.246809,38.020000,2.451064,9.085106,5.195745,1.310638,6.025532,15.421277,0.023607,-0.037803,0.510638,0.161702
B02,39.645522,5255.355112,63078.280709,7.936567,27.130597,20.868694,14.541306,0.839552,0.238806,37.321269,2.238806,8.996269,5.279851,1.205224,6.026119,15.328358,-0.012708,-0.028828,0.518657,0.141791
B03,41.146718,5589.874981,67060.601892,8.038610,27.486486,22.278880,15.066139,0.691120,0.351351,36.696525,2.552124,9.776062,5.100386,1.258687,6.057915,15.953668,0.078197,-0.005442,0.563707,0.162162
B04,39.169811,5092.008340,61126.968038,7.924528,27.079245,21.434377,15.006113,0.641509,0.267925,37.894340,2.384906,9.426415,5.354717,1.411321,5.939623,15.150943,0.008302,-0.005658,0.505660,0.139623
B05,39.539683,5457.503413,65454.897937,8.019841,27.563492,20.525516,15.074127,0.829365,0.253968,38.037698,2.567460,9.051587,5.396825,1.293651,5.988095,14.996032,-0.035949,-0.010597,0.511905,0.178571
B06,39.192635,5406.285779,64902.669547,7.903683,26.991501,21.730170,14.545552,0.796034,0.249292,37.288669,2.311615,9.546742,5.093484,1.311615,5.957507,14.920680,0.008227,-0.029516,0.501416,0.152975
B07,39.334356,5378.191994,64577.192730,8.024540,27.438650,21.629969,14.557239,0.812883,0.334356,35.618712,2.481595,9.389571,5.309816,1.340491,5.957055,15.273006,0.063428,0.020986,0.521472,0.236196
B08,38.936709,5665.908544,67987.409937,8.370253,28.382911,21.341519,14.467500,0.740506,0.319620,37.746203,2.455696,9.664557,5.582278,1.351266,6.022152,14.632911,-0.064384,-0.009787,0.537975,0.142405
B09,37.902027,5353.416689,64264.046182,7.908784,26.929054,21.541858,14.916520,0.824324,0.216216,38.088514,2.293919,9.138514,5.354730,1.337838,5.814189,14.293919,-0.053457,0.025434,0.425676,0.121622
B10,39.478114,5430.639461,65167.356263,8.080808,27.670034,21.634747,15.539933,0.808081,0.299663,37.448148,2.377104,9.447811,5.148148,1.417508,6.033670,14.666667,0.020132,-0.056496,0.484848,0.127946
B11,38.794702,5507.560331,66049.202781,7.880795,27.215232,21.727020,14.056026,0.807947,0.238411,37.349669,2.549669,9.274834,5.281457,1.360927,5.947020,15.341060,0.019484,0.005517,0.490066,0.076159
B12,39.420495,5340.978127,64074.360883,7.795053,26.590106,21.342473,15.232686,0.784452,0.243816,36.918728,2.434629,9.183746,4.957597,1.247350,5.893993,14.946996,-0.049388,-0.040863,0.522968,0.130742
B13,39.802013,5301.909161,63649.281846,8.010067,27.651007,21.386913,15.293188,0.768456,0.261745,36.229530,2.369128,9.208054,5.248322,1.335570,5.989933,15.000000,-0.029687,-0.042229,0.486577,0.144295
B14,39.077441,5408.123401,64905.740943,8.097643,27.350168,21.675926,16.273030,0.797980,0.326599,38.661616,2.457912,9.242424,5.329966,1.424242,6.030303,15.181818,0.035624,-0.007363,0.471380,0.121212
B15,40.106061,5472.551364,65613.768674,8.181818,27.757576,21.320568,15.268068,0.787879,0.314394,35.988258,2.564394,9.530303,5.571970,1.450758,6.185606,15.431818,0.030607,0.058929,0.511364,0.128788
B16,38.984424,5342.766729,64165.649034,7.984424,27.548287,22.491246,14.529533,0.825545,0.317757,36.224611,2.526480,9.124611,5.292835,1.283489,5.943925,14.713396,0.023372,0.002865,0.507788,0.149533
B17,38.274052,5126.670671,61495.294723,7.725948,26.728863,20.965394,15.222157,0.877551,0.268222,36.059184,2.431487,9.244898,5.119534,1.381924,6.198251,15.134111,-0.104621,-0.018015,0.454810,0.110787
B18,40.057143,5235.414771,62808.198886,7.951429,27.325714,21.913429,14.803743,0.897143,0.268571,36.475429,2.445714,9.037143,5.534286,1.354286,5.934286,14.397143,-0.088374,-0.007870,0.517143,0.120000
B19,39.417445,5480.589564,65785.094206,7.996885,27.299065,21.609782,15.239408,0.965732,0.264798,32.519315,2.395639,9.314642,5.246106,1.230530,5.890966,15.202492,-0.043269,-0.025060,0.495327,0.180685
B20,38.436170,5180.350080,62172.213059,7.984043,27.648936,21.801543,14.158723,0.922872,0.271277,36.505053,2.454787,9.146277,5.470745,1.268617,5.827128,15.207447,0.101743,0.040139,0.478723,0.154255
B21,38.900958,5436.203482,65235.887284,8.198083,27.884984,22.296326,15.182173,0.785942,0.313099,35.284026,2.613419,9.654952,5.584665,1.431310,6.000000,14.715655,-0.102685,-0.026840,0.495208,0.143770
B22,37.996587,5197.006075,62364.560717,7.877133,27.221843,22.204812,14.729147,0.805461,0.290102,36.997270,2.290102,9.293515,5.129693,1.368601,5.941980,15.075085,-0.055531,0.055043,0.587031,0.163823
B23,37.160714,5448.038929,65437.362393,7.742857,26.567857,21.811393,14.419321,0.782143,0.189286,36.046786,2.378571,9.050000,5.042857,1.410714,5.996429,15.475000,-0.086226,0.047650,0.492857,0.146429
B24,38.867347,5326.433639,63911.199728,8.156463,27.986395,21.423163,14.148095,0.761905,0.258503,35.236054,2.462585,9.374150,5.370748,1.326531,5.931973,14.299320,0.007802,0.009033,0.517007,0.142857
B25,39.666667,5599.780567,67147.724078,8.021277,27.765957,20.544504,15.288794,0.787234,0.255319,35.547872,2.563830,9.514184,5.308511,1.379433,5.890071,14.560284,-0.007848,0.014325,0.492908,0.152482
overall_data,39.139364,5365.462080,64388.796716,7.986638,27.373063,21.574357,14.895067,0.807456,0.274853,36.606534,2.441074,9.308926,5.295430,1.339391,5.974479,14.998397,-0.012931,-0.002729,0.503207,0.145110