In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import GroupShuffleSplit

from sklearn.linear_model import LogisticRegression

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [4]:
df = pd.read_csv("data/datav3.csv")
df.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [5]:
df.shape

(7519, 29)

# Independence of Observations

## Detection

### Repeated entities and Duplicated IDs

#### Duplicated IDs

In [6]:
df.duplicated().sum()

np.int64(35)

In [7]:
pd.set_option('display.max_rows', None)

In [8]:
exact_duplicates = df[df.duplicated(keep=False)]
exact_duplicates.sort_values(['customer_id', 'observation_month']).head(20)

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
5077,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
6080,CUST00501,2025-08-01,B08,33,3078.55,36733.47,4,14,33.36,1.40,2,0,5.8,2,10,2,0,5,13,Mobile,East,Dark,Bachelor,Organic,CMP04,-0.3185,-0.9865,0,0
731,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
999,CUST00605,2025-08-01,B13,62,5851.43,70200.80,11,40,17.22,7.82,2,0,19.5,1,13,5,1,6,8,Mobile,North,Dark,PhD,Organic,CMP02,-0.3049,-0.4817,1,0
5180,CUST00634,2026-01-01,B04,49,5360.73,64293.39,3,7,4.85,13.97,1,1,24.1,2,9,3,1,6,19,Mobile,Central,Dark,Master,Affiliate,CMP01,0.5543,0.4336,0,0
5830,CUST00634,2026-01-01,B04,49,5360.73,64293.39,3,7,4.85,13.97,1,1,24.1,2,9,3,1,6,19,Mobile,Central,Dark,Master,Affiliate,CMP01,0.5543,0.4336,0,0
2884,CUST00639,2026-01-01,B14,36,3496.38,42021.33,7,22,26.89,21.72,0,0,27.7,3,4,4,1,5,14,Mobile,North,Dark,High School,Referral,CMP01,-0.0494,0.0916,0,0
6333,CUST00639,2026-01-01,B14,36,3496.38,42021.33,7,22,26.89,21.72,0,0,27.7,3,4,4,1,5,14,Mobile,North,Dark,High School,Referral,CMP01,-0.0494,0.0916,0,0
1601,CUST00887,2026-02-01,B15,38,4849.39,58041.66,10,30,20.81,21.70,1,0,32.0,1,9,6,1,6,19,Mobile,North,Dark,Bachelor,Social,CMP02,0.5303,-0.0009,0,0
6975,CUST00887,2026-02-01,B15,38,4849.39,58041.66,10,30,20.81,21.70,1,0,32.0,1,9,6,1,6,19,Mobile,North,Dark,Bachelor,Social,CMP02,0.5303,-0.0009,0,0
3596,CUST01020,2025-04-01,B10,51,6311.86,76053.13,8,31,23.31,13.21,2,1,27.8,1,8,5,3,7,21,Desktop,East,Dark,Master,Search,CMP07,0.7241,-0.7363,0,0
4911,CUST01020,2025-04-01,B10,51,6311.86,76053.13,8,31,23.31,13.21,2,1,27.8,1,8,5,3,7,21,Desktop,East,Dark,Master,Search,CMP07,0.7241,-0.7363,0,0
2183,CUST01286,2025-01-01,B14,36,4039.88,48510.99,7,23,18.18,26.55,1,1,17.9,5,8,8,1,7,10,Tablet,North,System,Bachelor,Email,CMP60,0.1843,0.7257,0,0
5702,CUST01286,2025-01-01,B14,36,4039.88,48510.99,7,23,18.18,26.55,1,1,17.9,5,8,8,1,7,10,Tablet,North,System,Bachelor,Email,CMP60,0.1843,0.7257,0,0
3839,CUST01321,2025-08-01,B19,24,6345.16,76806.98,8,25,21.06,11.80,2,0,3.7,3,10,7,1,7,12,Mobile,South,Dark,Master,Social,CMP02,0.0926,-0.2380,1,0
6340,CUST01321,2025-08-01,B19,24,6345.16,76806.98,8,25,21.06,11.80,2,0,3.7,3,10,7,1,7,12,Mobile,South,Dark,Master,Social,CMP02,0.0926,-0.2380,1,0
1072,CUST01372,2025-10-01,B18,34,5263.53,63459.71,9,31,36.12,20.09,1,1,37.5,2,12,3,3,3,7,Desktop,South,Light,High School,Organic,CMP01,-0.9548,0.1328,1,0
3454,CUST01372,2025-10-01,B18,34,5263.53,63459.71,9,31,36.12,20.09,1,1,37.5,2,12,3,3,3,7,Desktop,South,Light,High School,Organic,CMP01,-0.9548,0.1328,1,0
2615,CUST01396,2025-08-01,B12,41,6756.68,81219.61,7,25,24.13,15.92,1,1,72.2,2,13,7,0,4,17,Tablet,North,Light,Master,Social,CMP01,-1.7677,-0.6401,0,0
6789,CUST01396,2025-08-01,B12,41,6756.68,81219.61,7,25,24.13,15.92,1,1,72.2,2,13,7,0,4,17,Tablet,North,Light,Master,Social,CMP01,-1.7677,-0.6401,0,0

they are exact duplicated columns, I will drop them

In [9]:
df_clean = df.drop_duplicates()

In [10]:
df_clean.shape

(7484, 29)

#### Repeated entities

In [11]:
customer_counts = df_clean['customer_id'].value_counts()
customer_counts.head()

customer_id
CUST03090    3
CUST02133    3
CUST01676    3
CUST03203    3
CUST02897    3
Name: count, dtype: int64

In [12]:
repeated_customers = customer_counts[customer_counts > 1]
len(repeated_customers)

1775

In [13]:
pd.set_option('display.max_rows', None)

In [14]:
repeated_customers_df =  df_clean[df_clean['customer_id'].isin(repeated_customers.index)].sort_values(by='customer_id')
repeated_customers_df.head(10)

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
630,CUST00001,2025-12-01,B17,40,14331.28,172408.24,6,21,32.13,10.34,1,0,8.2,2,12,4,1,5,8,Mobile,South,Dark,Master,Search,CMP01,0.4028,-0.3411,1,0
4953,CUST00001,2025-11-01,B17,40,14525.17,173291.39,9,31,23.24,10.14,1,0,47.9,1,13,4,3,7,18,Mobile,South,Dark,Master,Partner_Rare,CMP02,1.4404,0.7305,1,0
4195,CUST00003,2026-04-01,B15,31,2283.80,27365.68,7,24,31.83,11.54,1,0,44.1,2,9,6,1,6,11,Mobile,North,Light,High School,Social,CMP06,2.5045,-0.0049,0,0
6624,CUST00003,2026-05-01,B15,31,2359.29,28074.30,7,23,33.04,7.09,2,0,50.2,0,5,3,0,5,19,Mobile,North,Light,High School,Search,CMP01,-0.2593,-0.6711,1,0
3236,CUST00004,2026-02-01,B15,27,4735.69,56815.43,9,33,43.15,23.18,0,0,15.4,3,13,8,1,6,11,Mobile,North,Dark,Bachelor,Referral,CMP01,1.1225,-0.0007,0,0
5128,CUST00004,2026-03-01,B15,27,4576.81,54304.18,6,22,17.01,16.45,1,0,19.2,2,3,2,1,7,8,Mobile,North,Dark,Bachelor,Search,CMP33,0.7423,0.2380,0,0
7101,CUST00006,2025-06-01,B10,40,6764.86,80682.02,11,33,25.74,28.96,1,0,25.9,4,10,4,3,9,9,Desktop,East,Light,Bachelor,Social,CMP01,0.5939,0.2385,1,0
2215,CUST00006,2025-07-01,B10,40,6702.88,80338.78,8,31,25.39,27.59,0,0,35.9,4,12,4,0,3,12,Desktop,East,Light,Bachelor,Social,CMP03,-0.9011,-0.9781,0,0
3514,CUST00006,2025-05-01,B10,40,6758.65,81038.19,12,39,30.81,7.78,0,0,45.7,2,16,5,0,7,21,Desktop,East,Light,Bachelor,Search,CMP02,-0.4524,0.1382,0,0
1474,CUST00007,2026-02-01,B14,36,4494.10,54132.37,10,32,29.26,2.86,0,0,6.6,2,9,6,0,5,13,Mobile,North,Light,PhD,Affiliate,CMP08,-0.1623,0.3194,0,0

In [15]:
customer_counts.value_counts().sort_values()

count
3     509
2    1266
1    3425
Name: count, dtype: int64

In [16]:
df_clean[
    df_clean['customer_id'] == 'CUST00006'
][
    [
        'customer_id',
        'observation_month',
        'monthly_income',
        'purchased'
    ]
].sort_values('observation_month')

     customer_id observation_month  monthly_income  purchased
3514   CUST00006        2025-05-01         6758.65          0
7101   CUST00006        2025-06-01         6764.86          0
2215   CUST00006        2025-07-01         6702.88          0

they are not duplicated rows, they are legitimate repeated measurements.Same customers with different time points.                                         
Treatments:
- `Agrregation` if data has multiple lower-level rows, but we want unit of analysis should be higher-level.
- `Group-aware train/test splitting`

### Natural groups or clusters

In [17]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

`1. Does the dataset have a meaningful grouping structure ?`

In [18]:
df_clean['branch_id'].nunique()

25

In [19]:
df_clean['branch_id'].value_counts().sort_values()

branch_id
B01    235
B05    252
B03    259
B15    264
B04    265
B02    268
B23    280
B25    282
B12    283
B22    293
B24    294
B09    296
B10    297
B14    297
B13    298
B11    302
B21    313
B08    316
B16    321
B19    321
B07    326
B17    343
B18    350
B06    353
B20    376
Name: count, dtype: int64

In [20]:
# number of unique customers in each branch
df.groupby('branch_id')['customer_id'].nunique().sort_values()

branch_id
B01    158
B04    173
B05    174
B03    177
B02    179
B15    189
B25    194
B23    196
B12    199
B10    203
B14    203
B11    203
B24    204
B22    210
B13    211
B09    211
B07    218
B19    219
B08    226
B21    227
B16    231
B06    241
B18    245
B17    247
B20    262
Name: customer_id, dtype: int64

the dataset has a meaningful grouping structure because multiple different customers belong to the same branch.

`2. Are observations within a group more similar than observations across groups?`

In [21]:
branch_summary = (
    df.groupby('branch_id')
      .agg(
          customers=('customer_id', 'nunique'),
          observations=('customer_id', 'size'),
          purchase_rate=('purchased', 'mean')
      )
)

branch_summary.sort_values(by='purchase_rate')

           customers  observations  purchase_rate
branch_id
B11              203           303       0.075908
B17              247           344       0.110465
B14              203           299       0.120401
B09              211           298       0.120805
B18              245           352       0.122159
B10              203           299       0.127090
B15              189           267       0.127341
B12              199           284       0.130282
B04              173           267       0.138577
B02              179           269       0.141264
B08              226           318       0.141509
B24              204           294       0.142857
B21              227           313       0.143770
B13              211           301       0.146179
B23              196           281       0.149466
B16              231           321       0.149533
B25              194           282       0.152482
B20              262           379       0.153034
B06              241           355       0.154930
B03              177           261       0.160920
B01              158           235       0.161702
B22              210           295       0.162712
B05              174           253       0.177866
B19              219           323       0.182663
B07              218           326       0.236196

In [22]:
overall_purchase_rate = df['purchased'].mean()

overall_purchase_rate

np.float64(0.14509908232477722)

In [23]:
branch_rates = (
    df.groupby('branch_id')['purchased']
      .mean()
)

print("Min:", branch_rates.min())
print("Max:", branch_rates.max())
print("Std:", branch_rates.std())

Min: 0.07590759075907591
Max: 0.2361963190184049
Std: 0.029242373704262154

In [24]:
num_columns = ['age',
    'monthly_income', 
    'annual_income', 
    'website_visits_30d',
    'website_visits_90d', 
    'session_minutes', 
    'discount_pct',
    'support_tickets_30d', 
    'premium_member', 
    'days_since_last_purchase',
    'cart_items', 
    'email_opens_30d', 
    'profile_views_30d',
    'social_referrals_30d', 
    'survey_score', 
    'preferred_contact_hour',
    'noise_feature_1',
    'noise_feature_2', 
    'noise_feature_3', 
    'purchased']

In [25]:
braches_stats = df_clean.groupby('branch_id')[
    num_columns
].mean()

In [26]:
df_stats = df_clean[
    num_columns
].mean()

In [27]:
comparison_df = braches_stats.copy()
comparison_df.loc['overall_data'] = df_stats

In [28]:
comparison_df

,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,noise_feature_1,noise_feature_2,noise_feature_3,purchased
branch_id,,,,,,,,,,,,,,,,,,,,
B01,39.855319,5153.626213,61882.214298,7.851064,27.008511,21.443617,15.244638,0.731915,0.246809,38.020000,2.451064,9.085106,5.195745,1.310638,6.025532,15.421277,0.023607,-0.037803,0.510638,0.161702
B02,39.645522,5255.355112,63078.280709,7.936567,27.130597,20.868694,14.541306,0.839552,0.238806,37.321269,2.238806,8.996269,5.279851,1.205224,6.026119,15.328358,-0.012708,-0.028828,0.518657,0.141791
B03,41.146718,5589.874981,67060.601892,8.038610,27.486486,22.278880,15.066139,0.691120,0.351351,36.696525,2.552124,9.776062,5.100386,1.258687,6.057915,15.953668,0.078197,-0.005442,0.563707,0.162162
B04,39.169811,5092.008340,61126.968038,7.924528,27.079245,21.434377,15.006113,0.641509,0.267925,37.894340,2.384906,9.426415,5.354717,1.411321,5.939623,15.150943,0.008302,-0.005658,0.505660,0.139623
B05,39.539683,5457.503413,65454.897937,8.019841,27.563492,20.525516,15.074127,0.829365,0.253968,38.037698,2.567460,9.051587,5.396825,1.293651,5.988095,14.996032,-0.035949,-0.010597,0.511905,0.178571
B06,39.192635,5406.285779,64902.669547,7.903683,26.991501,21.730170,14.545552,0.796034,0.249292,37.288669,2.311615,9.546742,5.093484,1.311615,5.957507,14.920680,0.008227,-0.029516,0.501416,0.152975
B07,39.334356,5378.191994,64577.192730,8.024540,27.438650,21.629969,14.557239,0.812883,0.334356,35.618712,2.481595,9.389571,5.309816,1.340491,5.957055,15.273006,0.063428,0.020986,0.521472,0.236196
B08,38.936709,5665.908544,67987.409937,8.370253,28.382911,21.341519,14.467500,0.740506,0.319620,37.746203,2.455696,9.664557,5.582278,1.351266,6.022152,14.632911,-0.064384,-0.009787,0.537975,0.142405
B09,37.902027,5353.416689,64264.046182,7.908784,26.929054,21.541858,14.916520,0.824324,0.216216,38.088514,2.293919,9.138514,5.354730,1.337838,5.814189,14.293919,-0.053457,0.025434,0.425676,0.121622
B10,39.478114,5430.639461,65167.356263,8.080808,27.670034,21.634747,15.539933,0.808081,0.299663,37.448148,2.377104,9.447811,5.148148,1.417508,6.033670,14.666667,0.020132,-0.056496,0.484848,0.127946
B11,38.794702,5507.560331,66049.202781,7.880795,27.215232,21.727020,14.056026,0.807947,0.238411,37.349669,2.549669,9.274834,5.281457,1.360927,5.947020,15.341060,0.019484,0.005517,0.490066,0.076159
B12,39.420495,5340.978127,64074.360883,7.795053,26.590106,21.342473,15.232686,0.784452,0.243816,36.918728,2.434629,9.183746,4.957597,1.247350,5.893993,14.946996,-0.049388,-0.040863,0.522968,0.130742
B13,39.802013,5301.909161,63649.281846,8.010067,27.651007,21.386913,15.293188,0.768456,0.261745,36.229530,2.369128,9.208054,5.248322,1.335570,5.989933,15.000000,-0.029687,-0.042229,0.486577,0.144295
B14,39.077441,5408.123401,64905.740943,8.097643,27.350168,21.675926,16.273030,0.797980,0.326599,38.661616,2.457912,9.242424,5.329966,1.424242,6.030303,15.181818,0.035624,-0.007363,0.471380,0.121212
B15,40.106061,5472.551364,65613.768674,8.181818,27.757576,21.320568,15.268068,0.787879,0.314394,35.988258,2.564394,9.530303,5.571970,1.450758,6.185606,15.431818,0.030607,0.058929,0.511364,0.128788
B16,38.984424,5342.766729,64165.649034,7.984424,27.548287,22.491246,14.529533,0.825545,0.317757,36.224611,2.526480,9.124611,5.292835,1.283489,5.943925,14.713396,0.023372,0.002865,0.507788,0.149533
B17,38.274052,5126.670671,61495.294723,7.725948,26.728863,20.965394,15.222157,0.877551,0.268222,36.059184,2.431487,9.244898,5.119534,1.381924,6.198251,15.134111,-0.104621,-0.018015,0.454810,0.110787
B18,40.057143,5235.414771,62808.198886,7.951429,27.325714,21.913429,14.803743,0.897143,0.268571,36.475429,2.445714,9.037143,5.534286,1.354286,5.934286,14.397143,-0.088374,-0.007870,0.517143,0.120000
B19,39.417445,5480.589564,65785.094206,7.996885,27.299065,21.609782,15.239408,0.965732,0.264798,32.519315,2.395639,9.314642,5.246106,1.230530,5.890966,15.202492,-0.043269,-0.025060,0.495327,0.180685
B20,38.436170,5180.350080,62172.213059,7.984043,27.648936,21.801543,14.158723,0.922872,0.271277,36.505053,2.454787,9.146277,5.470745,1.268617,5.827128,15.207447,0.101743,0.040139,0.478723,0.154255
B21,38.900958,5436.203482,65235.887284,8.198083,27.884984,22.296326,15.182173,0.785942,0.313099,35.284026,2.613419,9.654952,5.584665,1.431310,6.000000,14.715655,-0.102685,-0.026840,0.495208,0.143770
B22,37.996587,5197.006075,62364.560717,7.877133,27.221843,22.204812,14.729147,0.805461,0.290102,36.997270,2.290102,9.293515,5.129693,1.368601,5.941980,15.075085,-0.055531,0.055043,0.587031,0.163823
B23,37.160714,5448.038929,65437.362393,7.742857,26.567857,21.811393,14.419321,0.782143,0.189286,36.046786,2.378571,9.050000,5.042857,1.410714,5.996429,15.475000,-0.086226,0.047650,0.492857,0.146429
B24,38.867347,5326.433639,63911.199728,8.156463,27.986395,21.423163,14.148095,0.761905,0.258503,35.236054,2.462585,9.374150,5.370748,1.326531,5.931973,14.299320,0.007802,0.009033,0.517007,0.142857
B25,39.666667,5599.780567,67147.724078,8.021277,27.765957,20.544504,15.288794,0.787234,0.255319,35.547872,2.563830,9.514184,5.308511,1.379433,5.890071,14.560284,-0.007848,0.014325,0.492908,0.152482
overall_data,39.139364,5365.462080,64388.796716,7.986638,27.373063,21.574357,14.895067,0.807456,0.274853,36.606534,2.441074,9.308926,5.295430,1.339391,5.974479,14.998397,-0.012931,-0.002729,0.503207,0.145110

In [29]:
braches_std = df_clean.groupby(by='branch_id')[
    num_columns
].std()

In [30]:
df_std = df_clean[
    num_columns
].std()

In [31]:
std_comparison_df = braches_std.copy()
std_comparison_df.loc['overall_data'] = df_std

std_comparison_df

,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,noise_feature_1,noise_feature_2,noise_feature_3,purchased
branch_id,,,,,,,,,,,,,,,,,,,,
B01,11.687725,2229.271651,26881.626595,2.799410,8.521462,10.358616,7.763017,0.862591,0.432075,24.811441,1.643671,3.554399,2.450358,1.254604,1.432001,5.749505,0.932206,0.583775,0.500954,0.368963
B02,11.741492,2108.244750,25340.724550,3.014274,8.810198,10.184501,7.323454,0.912052,0.427152,25.897699,1.553920,3.540560,2.451027,1.030822,1.402001,5.622688,0.964356,0.588585,0.500587,0.349488
B03,12.971708,2138.038198,25647.562071,3.093889,9.292971,11.293225,8.312282,0.847453,0.478317,28.881281,1.752126,3.307855,2.797694,1.154143,1.478701,5.644317,1.068789,0.610455,0.496885,0.369313
B04,10.932534,2162.973763,25869.365325,3.035454,9.268171,10.276355,7.763006,0.785627,0.443716,28.223239,1.681832,3.717697,2.589794,1.206306,1.399451,6.006298,0.956609,0.546553,0.500914,0.347251
B05,12.305637,2198.338703,26345.553461,2.916433,8.615280,10.104453,7.614628,0.860054,0.436146,25.686784,1.739915,3.548373,2.715103,1.129591,1.334442,5.752878,1.009056,0.614495,0.500853,0.383755
B06,11.089115,2024.682615,24245.785618,2.919724,8.593234,10.990163,7.694890,0.925206,0.433217,27.598156,1.703708,3.704834,2.756148,1.120220,1.506013,5.936161,0.905691,0.562244,0.500708,0.360474
B07,11.244493,2394.404663,28744.565581,3.220991,9.667117,11.123419,7.470921,0.879835,0.472490,25.648135,1.656121,3.686785,2.487945,1.143820,1.479500,5.413573,0.931035,0.587471,0.500307,0.425397
B08,11.666086,2476.571642,29706.660948,3.279412,9.520015,10.559021,7.442140,0.855832,0.467069,28.337786,1.765974,3.637740,2.658834,1.168379,1.424106,5.898996,1.029450,0.575209,0.499347,0.350019
B09,12.226417,2441.161169,29333.344376,3.187123,9.536995,9.743462,8.055469,0.869180,0.412361,26.413094,1.600243,3.847659,2.564261,1.173458,1.528021,5.888060,1.025707,0.564242,0.495282,0.327402
B10,11.830462,2105.536648,25303.031085,2.925921,8.913182,10.724453,8.053048,0.940925,0.458884,25.342420,1.690358,3.712398,2.567653,1.273733,1.504120,5.989856,0.931869,0.565412,0.500614,0.334594
B11,12.668961,2113.017067,25326.212254,2.907036,8.553721,11.677900,7.480116,0.905614,0.426819,26.819533,1.687116,3.459394,2.395369,1.191971,1.370249,5.304631,0.964556,0.572243,0.500731,0.265693
B12,12.123034,2201.299913,26418.589043,2.895407,8.816179,10.753798,7.379334,0.854383,0.430144,24.419240,1.617217,3.530237,2.226127,1.118328,1.392508,5.914942,1.018762,0.592652,0.500357,0.337715
B13,12.114676,2321.302802,27850.163304,3.230208,9.431608,10.661448,8.278747,0.866557,0.440324,23.850797,1.677135,3.780644,2.537015,1.166945,1.388953,5.895270,1.024176,0.563583,0.500661,0.351980
B14,10.942296,2222.013379,26679.559494,3.105231,9.300462,12.416993,8.083541,0.896462,0.469761,27.082679,1.686316,3.754522,2.471229,1.268838,1.434054,5.862784,0.939098,0.554852,0.500023,0.326924
B15,11.486979,2312.262720,27708.384697,3.277573,9.265514,10.197394,7.819844,0.902302,0.465156,24.212355,1.646410,3.708872,2.641172,1.250642,1.395137,6.020489,1.002571,0.567654,0.500820,0.335601
B16,11.793659,2218.995348,26659.000357,3.040827,8.971396,11.683985,7.349106,0.949063,0.466331,26.436075,1.682655,3.582516,2.569334,1.203124,1.531942,5.698035,0.983769,0.589630,0.500720,0.357170
B17,10.898822,2438.186326,29215.297745,2.988398,8.941621,10.281917,7.677792,1.032876,0.443681,25.801177,1.711793,3.628763,2.457890,1.160973,1.467503,5.838927,1.046064,0.571037,0.498681,0.314327
B18,11.266358,2298.750791,27569.885949,3.025287,9.171850,10.449396,7.806138,0.880051,0.443851,26.445601,1.516356,3.673071,2.675951,1.150643,1.395335,6.103172,1.009741,0.576445,0.500421,0.325427
B19,11.298515,2304.790689,27693.687938,3.082712,8.941702,9.938978,7.610719,0.978875,0.441914,24.322631,1.519410,3.714508,2.493465,1.119348,1.452566,5.804050,0.937936,0.612423,0.500759,0.385358
B20,11.840323,2180.017424,26195.579454,3.174861,9.335761,10.455314,7.198671,0.950457,0.445211,25.565555,1.630731,3.711228,2.803654,1.142943,1.454889,5.777616,0.992287,0.572977,0.500213,0.361675
B21,11.650345,2156.235087,25901.781850,3.007320,8.972869,11.830267,7.526800,0.874603,0.464497,25.866775,1.752492,3.652684,2.616520,1.249068,1.478478,5.631213,0.913477,0.592554,0.500778,0.351418
B22,11.918530,1963.737731,23558.628548,3.152286,9.243395,10.933269,7.525987,0.898841,0.454586,26.445766,1.663819,4.076645,2.480797,1.199588,1.382391,5.569716,1.045945,0.584512,0.493210,0.370748
B23,11.435932,2039.978169,24557.790371,3.064121,9.398908,11.113344,7.728641,0.938447,0.392437,25.949662,1.563325,3.614636,2.560722,1.163618,1.487097,5.732954,0.981427,0.552176,0.500844,0.354168
B24,11.036370,2009.407870,24099.797412,3.061822,9.051228,10.809931,7.865559,0.926171,0.438559,22.889170,1.698311,3.619648,2.590735,1.166444,1.443639,5.812679,1.008753,0.569093,0.500563,0.350524
B25,11.627166,2464.867861,29467.823775,3.056917,9.086487,10.533247,7.593900,0.918830,0.436816,25.274051,1.887731,4.021492,2.448152,1.097394,1.458308,6.055342,1.025107,0.572834,0.500838,0.360127
overall_data,11.671993,2229.268331,26750.945691,3.062289,9.096190,10.783797,7.696043,0.905648,0.446470,25.966610,1.669827,3.677966,2.568682,1.172423,1.444141,5.804697,0.986408,0.577578,0.500023,0.352235

The dataset has a natural grouping structure through branch_id, but branch statistics do not vary strongly enough to suggest substantial branch-level dependence. Therefore, there is little evidence that the independence assumption is seriously violated because of branch clustering.|

### Time dependence / Autocorrelation

In [32]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [33]:
monthly_purchase = (
    df_clean
    .groupby('observation_month')['purchased']
    .mean()
    .sort_index()
)
monthly_purchase

observation_month
2025-01-01    0.165049
2025-02-01    0.169951
2025-03-01    0.187970
2025-04-01    0.156682
2025-05-01    0.157175
2025-06-01    0.153846
2025-07-01    0.114679
2025-08-01    0.126168
2025-09-01    0.126667
2025-10-01    0.103524
2025-11-01    0.119658
2025-12-01    0.144828
2026-01-01    0.136919
2026-02-01    0.149533
2026-03-01    0.165909
2026-04-01    0.133333
2026-05-01    0.160584
2026-06-01    0.159170
Name: purchased, dtype: float64

autocorrelation

In [34]:
for lag in range(1, 7):
    print(lag, monthly_purchase.autocorr(lag=lag))

1 0.5798520406363326
2 0.4216308923984829
3 0.41294853738540116
4 -0.2694053676743011
5 -0.5412611272856774
6 -0.52611500852856

The monthly purchase rate shows moderate positive autocorrelation over short lags, especially lag 1, suggesting nearby months are related. Negative correlations at lags 5–6 may indicate a cyclical pattern, but with only 18 months of data this should be treated as exploratory rather than strong evidence.

### Check for spatial dependence

In [35]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [36]:
df_clean['region'].value_counts()

region
South      1711
East       1588
West       1462
North      1444
Central    1279
Name: count, dtype: int64

In [37]:
df_clean.groupby(by='region')['purchased'].mean()

region
Central    0.156372
East       0.157431
North      0.119806
South      0.142607
West       0.149795
Name: purchased, dtype: float64

There is some regional difference in purchase rates, especially for the North region, but the differences are not large enough by themselves to indicate strong spatial dependence.

## Data Preparation

In [38]:
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0

In [39]:
df_clean.shape

(7484, 29)

In [40]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 7484 entries, 0 to 7518
Data columns (total 29 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               7484 non-null   str
 1   observation_month         7484 non-null   str
 2   branch_id                 7484 non-null   str
 3   age                       7484 non-null   int64
 4   monthly_income            7484 non-null   float64
 5   annual_income             7484 non-null   float64
 6   website_visits_30d        7484 non-null   int64
 7   website_visits_90d        7484 non-null   int64
 8   session_minutes           7484 non-null   float64
 9   discount_pct              7484 non-null   float64
 10  support_tickets_30d       7484 non-null   int64
 11  premium_member            7484 non-null   int64
 12  days_since_last_purchase  7484 non-null   float64
 13  cart_items                7484 non-null   int64
 14  email_opens_30d           7484 non-null   int64
 15  profile_views_30d         7484 non-null   int64
 16  social_referrals_30d      7484 non-null   int64
 17  survey_score              7484 non-null   int64
 18  preferred_contact_hour    7484 non-null   int64
 19  device_type               7484 non-null   str
 20  region                    7484 non-null   str
 21  app_theme                 7484 non-null   str
 22  education_level           7484 non-null   str
 23  marketing_channel         7484 non-null   str
 24  campaign_code             7484 non-null   str
 25  noise_feature_1           7484 non-null   float64
 26  noise_feature_2           7484 non-null   float64
 27  noise_feature_3           7484 non-null   int64
 28  purchased                 7484 non-null   int64
dtypes: float64(7), int64(13), str(9)
memory usage: 1.7 MB

### Dummpy Encoding

In [41]:
cate_df = df_clean[['device_type', 'region', 'app_theme', 'marketing_channel']]
cate_df.head()

  device_type   region app_theme marketing_channel
0     Desktop     West      Dark           Organic
1      Mobile  Central    System             Email
2      Mobile    North     Light           Organic
3      Mobile  Central      Dark            Social
4     Desktop    South      Dark            Search

In [42]:
dumpy_encoded_df = pd.get_dummies(
    cate_df,
    drop_first=True,
    dtype=int
)
dumpy_encoded_df.head()

,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [43]:
df_clean = pd.concat([df_clean, dumpy_encoded_df], axis=1)
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,Bachelor,Organic,CMP60,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,Bachelor,Email,CMP02,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,Master,Organic,CMP04,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,Bachelor,Social,CMP10,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,Bachelor,Search,CMP01,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

### Ordinary Encoding

In [44]:
df_clean['education_level'].value_counts()

education_level
Bachelor       3125
High School    2081
Master         1761
PhD             517
Name: count, dtype: int64

In [45]:
education_level_mapping = {
    "High School":1,
    "Bachelor":2,
    "Master":3,
    "PhD":4
}
df_clean['education_level'] = df_clean['education_level'].map(education_level_mapping)
df_clean.head()

,customer_id,observation_month,branch_id,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,device_type,region,app_theme,education_level,marketing_channel,campaign_code,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST01723,2026-06-01,B24,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,Desktop,West,Dark,2,Organic,CMP60,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,CUST03090,2025-11-01,B05,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,Mobile,Central,System,2,Email,CMP02,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,CUST04684,2026-01-01,B13,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,Mobile,North,Light,3,Organic,CMP04,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,CUST01687,2025-03-01,B05,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,Mobile,Central,Dark,2,Social,CMP10,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,CUST00535,2025-11-01,B17,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,Desktop,South,Dark,2,Search,CMP01,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [46]:
dropping_columns = ['device_type', 'region', 'app_theme', 'marketing_channel', 'branch_id', 'campaign_code']

df_clean = df_clean.drop(columns=dropping_columns)

In [47]:
df_ids = df_clean.copy()

In [48]:
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST01723,2026-06-01,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,CUST03090,2025-11-01,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,CUST04684,2026-01-01,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,CUST01687,2025-03-01,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,CUST00535,2025-11-01,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

### Timestamp column

Observation-month data is  in timestamp format like '2022-02-08'. We need to convert it into numeric values: How many months have passed since the first date in the dataset.

In [49]:
df_clean['observation_month'] = pd.to_datetime(
    df_clean['observation_month']
)

# getting the start date of data 
start_date = df_clean['observation_month'].min() 

# calculating 
df_clean['observation_month'] = (
    (df_clean['observation_month'].dt.year - start_date.year) * 12
    + 
    (df_clean['observation_month'].dt.month - start_date.month)
)
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

### Standardization

In [50]:
def z_score_stand(data):
    mean = data.mean()
    std = data.std()

    return (data - mean) / std

## Treatment

### Agrregation

When to apply this method: `if data has multiple lower-level rows, but we want unit of analysis should be higher-level.`
- now `one row = customer-month`, but we want to model `one row = customer=year`

In [51]:
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

In [52]:
df_ids['observation_month'] = pd.to_datetime(df_ids['observation_month'])
df_clean['year'] = df_ids['observation_month'].dt.year
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social,year
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,2026
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,2025
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,2026
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2025
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,2025

In [53]:
customer_year_df = (
    df_clean
    .groupby(['customer_id', 'year'])
    .agg(
        age=('age', 'last'),

        monthly_income=('monthly_income', 'mean'),
        annual_income=('annual_income', 'mean'),

        website_visits_30d=('website_visits_30d', 'mean'),
        website_visits_90d=('website_visits_90d', 'mean'),

        session_minutes=('session_minutes', 'mean'),
        discount_pct=('discount_pct', 'mean'),
        support_tickets_30d=('support_tickets_30d', 'mean'),

        premium_member=('premium_member', 'last'),
        days_since_last_purchase=('days_since_last_purchase', 'last'),

        cart_items=('cart_items', 'mean'),
        email_opens_30d=('email_opens_30d', 'mean'),
        profile_views_30d=('profile_views_30d', 'mean'),
        social_referrals_30d=('social_referrals_30d', 'mean'),

        survey_score=('survey_score', 'mean'),
        preferred_contact_hour=('preferred_contact_hour', 'last'),

        education_level=('education_level', 'last'),

        noise_feature_1=('noise_feature_1', 'mean'),
        noise_feature_2=('noise_feature_2', 'mean'),
        noise_feature_3=('noise_feature_3', 'mean'),

        purchased=('purchased', 'max'),

        device_type_Mobile=('device_type_Mobile', 'last'),
        device_type_Tablet=('device_type_Tablet', 'last'),

        region_East=('region_East', 'last'),
        region_North=('region_North', 'last'),
        region_South=('region_South', 'last'),
        region_West=('region_West', 'last'),

        app_theme_Light=('app_theme_Light', 'last'),
        app_theme_System=('app_theme_System', 'last'),

        marketing_channel_Email=('marketing_channel_Email', 'last'),
        marketing_channel_Organic=('marketing_channel_Organic', 'last'),
        marketing_channel_Partner_Rare=('marketing_channel_Partner_Rare', 'last'),
        marketing_channel_Referral=('marketing_channel_Referral', 'last'),
        marketing_channel_Search=('marketing_channel_Search', 'last'),
        marketing_channel_Social=('marketing_channel_Social', 'last')
    )
    .reset_index()
)

In [54]:
customer_year_df.head()

,customer_id,year,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,CUST00001,2025,40,14428.225,172849.815,7.5,26.0,27.685,10.240,1.0,0,47.9,1.5,12.5,4.0,2.0,6.0,18,3,0.9216,0.19470,1.0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0
1,CUST00002,2025,49,4940.630,59718.200,6.0,23.0,20.980,22.280,0.0,0,26.6,0.0,4.0,1.0,2.0,4.0,17,3,1.0422,-0.83910,0.0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0
2,CUST00003,2026,31,2321.545,27719.990,7.0,23.5,32.435,9.315,1.5,0,50.2,1.0,7.0,4.5,0.5,5.5,19,1,1.1226,-0.33800,0.5,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0
3,CUST00004,2026,27,4656.250,55559.805,7.5,27.5,30.080,19.815,0.5,0,19.2,2.5,8.0,5.0,1.0,6.5,8,2,0.9324,0.11865,0.0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0
4,CUST00005,2025,31,4199.810,50368.140,12.0,40.0,15.960,12.420,0.0,1,60.0,3.0,17.0,9.0,1.0,5.0,8,3,0.3404,0.60730,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [55]:
customer_year_df = customer_year_df.drop(columns=['customer_id', 'year'])

customer_year_df.head()

,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social
0,40,14428.225,172849.815,7.5,26.0,27.685,10.240,1.0,0,47.9,1.5,12.5,4.0,2.0,6.0,18,3,0.9216,0.19470,1.0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0
1,49,4940.630,59718.200,6.0,23.0,20.980,22.280,0.0,0,26.6,0.0,4.0,1.0,2.0,4.0,17,3,1.0422,-0.83910,0.0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0
2,31,2321.545,27719.990,7.0,23.5,32.435,9.315,1.5,0,50.2,1.0,7.0,4.5,0.5,5.5,19,1,1.1226,-0.33800,0.5,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0
3,27,4656.250,55559.805,7.5,27.5,30.080,19.815,0.5,0,19.2,2.5,8.0,5.0,1.0,6.5,8,2,0.9324,0.11865,0.0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0
4,31,4199.810,50368.140,12.0,40.0,15.960,12.420,0.0,1,60.0,3.0,17.0,9.0,1.0,5.0,8,3,0.3404,0.60730,1.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

### Agrregation modeling

In [56]:
X = customer_year_df.drop(columns='purchased')
y = customer_year_df['purchased']

X_stand = z_score_stand(X)

In [57]:
def splitting_data(X, y, test_percentage=0.2):
    train_pc = 1 - test_percentage
    n = len(X)

    np.random.seed(42)
    indices = np.random.permutation(n)

    X_shuffled = X.iloc[indices]
    y_shuffled = y.iloc[indices] 

    X_train = X_shuffled[:int(train_pc * n)]
    y_train = y_shuffled[:int(train_pc * n)]

    X_test = X_shuffled[int(train_pc * n):]
    y_test = y_shuffled[int(train_pc * n):]

    return X_train, X_test, y_train, y_test

In [58]:
X_train, X_test, y_train, y_test = splitting_data(X_stand, y)
print(f"Train data records {X_train.shape}")
print(f"Test data records: {X_test.shape}")

print(f"Train y: {y_train.shape}")
print(f"Test y: {y_test.shape}")

Train data records (4272, 34)
Test data records: (1068, 34)
Train y: (4272,)
Test y: (1068,)

In [59]:
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [60]:
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)

confusion_matrix = pd.DataFrame(
    columns=['aggregated-data-model'],
    index=['Train_TP', "Train_TN", "Train_FP", "Train_FN", 'Test_TP', "Test_TN", "Test_FP", "Test_FN"]
)

train_TP = np.sum((train_predictions == 1) & (y_train == 1))
train_TN = np.sum((train_predictions == 0) & (y_train == 0))
train_FP = np.sum((train_predictions == 1) & (y_train == 0))
train_FN = np.sum((train_predictions == 0) & (y_train == 1))

test_TP = np.sum((test_predictions == 1) & (y_test == 1))
test_TN = np.sum((test_predictions == 0) & (y_test == 0))
test_FP = np.sum((test_predictions == 1) & (y_test == 0 ))
test_FN = np.sum((test_predictions == 0) & (y_test == 1))

confusion_matrix.loc['Train_TP'] = train_TP
confusion_matrix.loc['Train_TN'] = train_TN     
confusion_matrix.loc['Train_FP'] = train_FP
confusion_matrix.loc['Train_FN'] = train_FN

confusion_matrix.loc['Test_TP'] = test_TP
confusion_matrix.loc['Test_TN'] = test_TN
confusion_matrix.loc['Test_FP'] = test_FP
confusion_matrix.loc['Test_FN'] = test_FN

confusion_matrix

         aggregated-data-model
Train_TP                   111
Train_TN                  3400
Train_FP                    74
Train_FN                   687
Test_TP                     26
Test_TN                    841
Test_FP                     21
Test_FN                    180

In [61]:
models_restuls = pd.DataFrame(
    columns=['aggregated-data-model'],
    index=[
        'train-accuracy',
        'train-balanced-accuracy',
        'train-precision',
        'train-recall',
        'train-F1-score',
        'test-accuracy',
        'test-balanced-accuracy',
        'test-precision',
        'test-recall',
        'test-F1-score'
    ])


train_accuracy = (train_TP + train_TN) / (train_TP + train_TN + train_FP + train_FN)
train_balanced_acc = 1/2 * (train_TP / (train_TP + train_FN) + train_TN / (train_TN + train_FP))
train_precision = train_TP / (train_TP + train_FP)
train_recall = train_TP / (train_TP + train_FN)
train_F1_score = 2 *((train_precision * train_recall) / (train_precision + train_recall))

test_accuracy = (test_TP + test_TN) / (test_TP + test_TN + test_FP + test_FN)
test_balanced_acc = 1/2 * (test_TP / (test_TP + test_FN) + test_TN / (test_TN + test_FP))
test_precision = test_TP / (test_TP + test_FP)
test_recall = test_TP / (test_TP + test_FN)
test_F1_score = 2 * ((test_precision * test_recall) / (test_precision + test_recall))


models_restuls.loc['train-accuracy'] = train_accuracy
models_restuls.loc['train-balanced-accuracy'] = train_balanced_acc
models_restuls.loc['train-precision'] = train_precision
models_restuls.loc['train-recall'] = train_recall
models_restuls.loc['train-F1-score'] = train_F1_score
models_restuls.loc['test-accuracy'] = test_accuracy
models_restuls.loc['test-balanced-accuracy'] = test_balanced_acc
models_restuls.loc['test-precision'] = test_precision
models_restuls.loc['test-recall'] = test_recall
models_restuls.loc['test-F1-score'] = test_F1_score

models_restuls

                        aggregated-data-model
train-accuracy                       0.821863
train-balanced-accuracy              0.558898
train-precision                           0.6
train-recall                         0.139098
train-F1-score                       0.225839
test-accuracy                        0.811798
test-balanced-accuracy               0.550926
test-precision                       0.553191
test-recall                          0.126214
test-F1-score                        0.205534

### Group-aware train-test split

In [62]:
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social,year
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,2026
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,2025
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,2026
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2025
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,2025

In [63]:
df_clean.shape

(7484, 38)

In [64]:
groups = df_clean['customer_id']

X = df_clean.drop(columns=['customer_id', 'purchased'])
y = df_clean['purchased']

In [65]:
X_stand = z_score_stand(X)

In [66]:
gss = GroupShuffleSplit(
    n_splits=1,
    test_size=0.20,
    random_state=42
)

train_idx, test_idx = next(
    gss.split(
        X_stand,
        y,
        groups=groups
    )
)

In [67]:
X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]

y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

In [68]:
groups_train = groups.iloc[train_idx]
groups_test = groups.iloc[test_idx]

In [69]:
train_customers = set(groups_train)
test_customers = set(groups_test)

train_customers.intersection(test_customers)

set()

### Group-aware train-test split model

In [70]:
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

c:\Users\k\anaconda3\envs\creditrisk\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 5000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=5000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=5000)

In [71]:
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)


train_TP = np.sum((train_predictions == 1) & (y_train == 1))
train_TN = np.sum((train_predictions == 0) & (y_train == 0))
train_FP = np.sum((train_predictions == 1) & (y_train == 0))
train_FN = np.sum((train_predictions == 0) & (y_train == 1))

test_TP = np.sum((test_predictions == 1) & (y_test == 1))
test_TN = np.sum((test_predictions == 0) & (y_test == 0))
test_FP = np.sum((test_predictions == 1) & (y_test == 0 ))
test_FN = np.sum((test_predictions == 0) & (y_test == 1))

confusion_matrix['Group-aware-train-test-split-model'] = [
    train_TP,
    train_TN,
    train_FP,
    train_FN,
    test_TP,
    test_TN,
    test_FP,
    test_FN
]
confusion_matrix

         aggregated-data-model  Group-aware-train-test-split-model
Train_TP                   111                                  80
Train_TN                  3400                                5077
Train_FP                    74                                  51
Train_FN                   687                                 777
Test_TP                     26                                  15
Test_TN                    841                                1258
Test_FP                     21                                  12
Test_FN                    180                                 214

In [72]:
train_accuracy = (train_TP + train_TN) / (train_TP + train_TN + train_FP + train_FN)
train_balanced_acc = 1/2 * (train_TP / (train_TP + train_FN) + train_TN / (train_TN + train_FP))
train_precision = train_TP / (train_TP + train_FP)
train_recall = train_TP / (train_TP + train_FN)
train_F1_score = 2 *((train_precision * train_recall) / (train_precision + train_recall))

test_accuracy = (test_TP + test_TN) / (test_TP + test_TN + test_FP + test_FN)
test_balanced_acc = 1/2 * (test_TP / (test_TP + test_FN) + test_TN / (test_TN + test_FP))
test_precision = test_TP / (test_TP + test_FP)
test_recall = test_TP / (test_TP + test_FN)
test_F1_score = 2 * ((test_precision * test_recall) / (test_precision + test_recall))


models_restuls['Group-aware-train-test-split-model'] = [
    train_accuracy,
    train_balanced_acc,
    train_precision,
    train_recall,
    train_F1_score,
    test_accuracy,
    test_balanced_acc,
    test_precision,
    test_recall,
    test_F1_score
]

models_restuls

,aggregated-data-model,Group-aware-train-test-split-model
train-accuracy,0.821863,0.861654
train-balanced-accuracy,0.558898,0.541702
train-precision,0.6,0.610687
train-recall,0.139098,0.093349
train-F1-score,0.225839,0.161943
test-accuracy,0.811798,0.849233
test-balanced-accuracy,0.550926,0.528027
test-precision,0.553191,0.555556
test-recall,0.126214,0.065502
test-F1-score,0.205534,0.117188

### Time-based splitting

In [73]:
df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social,year
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,2026
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,2025
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,2026
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2025
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,2025

In [74]:
df_clean['observation_month_date'] = df_ids['observation_month']

df_clean.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social,year,observation_month_date
0,CUST01723,17,57,4144.46,49861.80,8,25,18.74,9.01,3,1,16.1,2,11,2,1,5,17,2,-0.3758,0.7415,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,2026,2026-06-01
1,CUST03090,10,39,3313.13,39964.60,7,27,12.38,7.64,1,1,6.6,0,11,6,1,7,8,2,-0.6708,0.5766,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,2025,2025-11-01
2,CUST04684,12,51,4965.57,58703.65,3,15,8.97,15.84,3,0,55.0,0,3,5,1,4,8,3,0.2868,-0.6751,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,2026,2026-01-01
3,CUST01687,2,56,2045.66,24364.68,7,24,30.73,10.50,0,0,22.8,0,6,8,0,5,8,2,2.1992,0.8292,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,2025,2025-03-01
4,CUST00535,10,31,4355.62,51882.27,10,29,31.40,2.09,0,0,40.1,1,10,4,0,8,8,2,-1.2592,-0.1662,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,2025,2025-11-01

In [75]:
df_clean['observation_month_date'] = pd.to_datetime(
    df_clean['observation_month_date']
)

In [76]:
df_time = df_clean.sort_values(
    'observation_month'
).copy()

In [77]:
cutoff_date = pd.Timestamp('2026-03-01')


train_df = df_time[
    df_time['observation_month_date'] < cutoff_date
].copy()

test_df = df_time[
    df_time['observation_month_date'] >= cutoff_date
].copy()

In [78]:
train_df.head()

,customer_id,observation_month,age,monthly_income,annual_income,website_visits_30d,website_visits_90d,session_minutes,discount_pct,support_tickets_30d,premium_member,days_since_last_purchase,cart_items,email_opens_30d,profile_views_30d,social_referrals_30d,survey_score,preferred_contact_hour,education_level,noise_feature_1,noise_feature_2,noise_feature_3,purchased,device_type_Mobile,device_type_Tablet,region_East,region_North,region_South,region_West,app_theme_Light,app_theme_System,marketing_channel_Email,marketing_channel_Organic,marketing_channel_Partner_Rare,marketing_channel_Referral,marketing_channel_Search,marketing_channel_Social,year,observation_month_date
6258,CUST02076,0,54,9441.08,113268.12,12,42,38.90,31.94,0,1,24.4,5,12,7,1,6,18,3,-0.3522,-0.0737,1,1,1,0,1,0,0,0,1,0,0,1,0,0,0,0,2025,2025-01-01
6253,CUST01380,0,41,8044.30,96575.77,9,33,27.45,8.82,1,0,33.6,0,6,8,1,6,11,4,-0.3078,0.4938,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,2025,2025-01-01
2892,CUST01644,0,57,11312.53,136360.28,4,19,7.26,16.35,1,0,44.8,2,3,3,0,5,21,3,-0.0423,-0.0699,1,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,2025,2025-01-01
2891,CUST04393,0,19,6204.29,74760.92,5,15,33.59,28.15,0,0,47.6,4,6,5,0,4,20,2,1.2994,-0.8592,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,2025,2025-01-01
4338,CUST04974,0,38,3353.98,40335.92,11,35,26.16,21.96,1,0,48.6,5,10,6,4,7,20,2,0.1685,-0.3385,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,2025,2025-01-01

In [87]:
train_df['observation_month_date'].value_counts().sort_index()

observation_month_date
2025-01-01    309
2025-02-01    406
2025-03-01    399
2025-04-01    434
2025-05-01    439
2025-06-01    429
2025-07-01    436
2025-08-01    428
2025-09-01    450
2025-10-01    454
2025-11-01    468
2025-12-01    435
2026-01-01    409
2026-02-01    428
Name: count, dtype: int64

In [86]:
test_df['observation_month_date'].value_counts().sort_index()

observation_month_date
2026-03-01    440
2026-04-01    420
2026-05-01    411
2026-06-01    289
Name: count, dtype: int64

In [92]:
X_train = train_df.drop(columns=['customer_id','year', 'purchased', 'observation_month_date'])
y_train = train_df['purchased']

X_test = test_df.drop(columns=['customer_id', 'year', 'purchased', 'observation_month_date'])
y_test = test_df['purchased']

X_train = z_score_stand(X_train)
X_test = z_score_stand(X_test)

print(f"Train: {X_train.shape}")
print(f"Test: {X_test.shape}")

Train: (5924, 35)
Test: (1560, 35)

### Time-based split modelling

In [93]:
X_train = z_score_stand(X_train)
X_test = z_score_stand(X_test)

In [94]:
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [95]:
train_predictions = model.predict(X_train)
test_predictions = model.predict(X_test)


train_TP = np.sum((train_predictions == 1) & (y_train == 1))
train_TN = np.sum((train_predictions == 0) & (y_train == 0))
train_FP = np.sum((train_predictions == 1) & (y_train == 0))
train_FN = np.sum((train_predictions == 0) & (y_train == 1))

test_TP = np.sum((test_predictions == 1) & (y_test == 1))
test_TN = np.sum((test_predictions == 0) & (y_test == 0))
test_FP = np.sum((test_predictions == 1) & (y_test == 0 ))
test_FN = np.sum((test_predictions == 0) & (y_test == 1))

confusion_matrix['Time-based-split-model'] = [
    train_TP,
    train_TN,
    train_FP,
    train_FN,
    test_TP,
    test_TN,
    test_FP,
    test_FN
]
confusion_matrix

,aggregated-data-model,Group-aware-train-test-split-model,Time-based-split-model
Train_TP,111,80,102
Train_TN,3400,5077,5013
Train_FP,74,51,66
Train_FN,687,777,743
Test_TP,26,15,21
Test_TN,841,1258,1302
Test_FP,21,12,17
Test_FN,180,214,220

In [96]:
train_accuracy = (train_TP + train_TN) / (train_TP + train_TN + train_FP + train_FN)
train_balanced_acc = 1/2 * (train_TP / (train_TP + train_FN) + train_TN / (train_TN + train_FP))
train_precision = train_TP / (train_TP + train_FP)
train_recall = train_TP / (train_TP + train_FN)
train_F1_score = 2 *((train_precision * train_recall) / (train_precision + train_recall))

test_accuracy = (test_TP + test_TN) / (test_TP + test_TN + test_FP + test_FN)
test_balanced_acc = 1/2 * (test_TP / (test_TP + test_FN) + test_TN / (test_TN + test_FP))
test_precision = test_TP / (test_TP + test_FP)
test_recall = test_TP / (test_TP + test_FN)
test_F1_score = 2 * ((test_precision * test_recall) / (test_precision + test_recall))


models_restuls['Time-based-split-model'] = [
    train_accuracy,
    train_balanced_acc,
    train_precision,
    train_recall,
    train_F1_score,
    test_accuracy,
    test_balanced_acc,
    test_precision,
    test_recall,
    test_F1_score
]

models_restuls

,aggregated-data-model,Group-aware-train-test-split-model,Time-based-split-model
train-accuracy,0.821863,0.861654,0.863437
train-balanced-accuracy,0.558898,0.541702,0.553858
train-precision,0.6,0.610687,0.607143
train-recall,0.139098,0.093349,0.120710
train-F1-score,0.225839,0.161943,0.201382
test-accuracy,0.811798,0.849233,0.848077
test-balanced-accuracy,0.550926,0.528027,0.537124
test-precision,0.553191,0.555556,0.552632
test-recall,0.126214,0.065502,0.087137
test-F1-score,0.205534,0.117188,0.150538